In [207]:
import os
import re
from pathlib import Path
from functools import reduce
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor

# Display settings
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_columns', 100)
sns.set(style='whitegrid')

# Logging
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.info("Notebook started.")

INFO:__main__:Notebook started.

# Paths

In [208]:
# Define paths
DATA_DIR = "../data/raw"
PROCESSED_DIR = "../data/processed"

# 1. Description File

In [209]:
file_path_desc = os.path.join(DATA_DIR, "call-report-data-2024-03/AcctDesc.txt") 

try:
    acct_description = pd.read_csv(file_path_desc)
    logger.info(f"Loaded dataset with shape {acct_description.shape}")
except Exception as e:
    logger.error(f"Failed to load file: {e}")

INFO:__main__:Loaded dataset with shape (3377, 12)

In [210]:
acct_description.head()
acct_description.columns

,Account,AcctName,AcctDesc,TableName,Annualize,CBSAccount,FPRAccount,STATAcctMain,STATAcctState,STATAcctGraph,STATAcctTable8,STATUS
0,Acct_001,Amount - Total Other Loans (Purchased or to no...,Include the dollar amount of outstanding loans...,FS220A,False,True,True,True,True,False,False,Inactive
1,Acct_002,Amount of Leases Receivable,"Leases Receivable. Include the rate, number, a...",FS220A,False,False,False,False,False,False,False,Active
2,Acct_003,Loans Held for Sale,Loans Held for Sale. Report the amount of outs...,FS220C,False,False,False,False,False,False,False,Active
3,Acct_007,Land and Building,"Land and building, less depreciation on buildi...",FS220,False,True,True,True,True,False,True,Active
4,Acct_008,Other Fixed Assets,All other fixed assets such as furniture and f...,FS220,False,True,True,True,True,False,True,Active

Index(['Account', 'AcctName', 'AcctDesc', 'TableName', 'Annualize',
       'CBSAccount', 'FPRAccount', 'STATAcctMain', 'STATAcctState',
       'STATAcctGraph', 'STATAcctTable8', 'STATUS'],
      dtype='object')

### Explaining Column Names

**What is a Call Report System?** 

In the context of credit unions, the Call Report System refers to a standardized reporting framework where credit unions submit detailed financial and operational data to regulators. It’s similar to the quarterly reports that banks submit to the FDIC.

**What It Contains**

The Call Report collects comprehensive data about a credit union’s:

1. Balance sheet (assets, liabilities, capital)

2. Income statement (interest income, non-interest income, expenses)

3. Lending activity (types of loans, delinquency, charge-offs)

4. Shares and deposits

5. Investment portfolio

6. Operational metrics (membership size, net worth ratio, loan-to-share ratio, delinquency ratios, etc.)




**CBSAccount**	Indicates whether the account is used in the Call Report system (CBS) — the core regulatory report that credit unions submit to the NCUA. Usually True/False.

**FPRAccount**	Flags whether this account is included in the Financial Performance Report (FPR), which summarizes key performance indicators.

**STATAcctMain**	True if the account is used in the main statistical report by the NCUA or analysts. Typically part of core metrics used for national trends.

**STATAcctState**	True if the account is used for state-level summaries or reports.

**STATAcctGraph**	True if the account is used in visualizations/graphs in published reports (like NCUA's quarterly charts).

**STATAcctTable8**	True if the account appears in Table 8 of NCUA’s standard reporting tables (one of the summary tables presented each quarter).

# Defining and Understanding KPIs

1. **Financial Health KPIs**

These measure profitability, stability, and overall balance sheet performance:

Net Worth Ratio (Capital Adequacy) → Net worth ÷ Total assets. Regulators (like NCUA in the U.S.) expect ≥7% to be considered “well-capitalized.”

Return on Assets (ROA) → Net income ÷ Average total assets. Shows profitability relative to asset size.

Loan-to-Share Ratio (LTS) → Loans outstanding ÷ Member shares. Measures lending aggressiveness vs. liquidity.

Delinquency Ratio → Delinquent loans ÷ Total loans. Indicates credit risk.

Charge-Off Ratio → Net charge-offs ÷ Average loans. Tracks loan losses.

Operating Expense Ratio → Operating expenses ÷ Average assets. Lower is better for efficiency.

2. **Liquidity & Risk KPIs**
Net Interest Margin (NIM) → (Interest income − Interest expense) ÷ Average earning assets.

Liquidity Ratio → Liquid assets ÷ Total assets. Ensures the CU can meet withdrawals.

Allowance for Loan Losses (ALLL) Coverage Ratio → ALLL ÷ Delinquent loans.

3. **Membership & Growth KPIs**
Credit unions are member-focused, so growth and engagement matter:

Membership Growth Rate → (New members − Exiting members) ÷ Total members.

Average Member Relationship (AMR) → Total loans + Shares ÷ Members. Measures product penetration.

Product Penetration Rate → e.g., % of members with checking, loans, or credit cards.

Share Growth Rate → Member deposits growth.

Loan Growth Rate → Year-over-year loan growth.

4. **Member Satisfaction KPIs**
Net Promoter Score (NPS) → Measures member loyalty and likelihood to recommend.

Member Retention Rate → % of members who stay year-over-year.

Digital Engagement Metrics → Online banking/mobile usage rates.

5. **Regulatory/Compliance KPIs**
CAMEL Ratings (Capital, Asset quality, Management, Earnings, Liquidity) – used by regulators.

Concentration Ratios → Limits on certain loan categories (e.g., real estate).

# Create a Mapping of Accounts and Their Names From The Description Files

In [211]:
acct_map = acct_description.set_index('Account')['AcctName'].dropna().to_dict()

{'Acct_001': 'Amount - Total Other Loans (Purchased or to non-members)', </br>
 'Acct_002': 'Amount of Leases Receivable',</br>
 'Acct_003': 'Loans Held for Sale',</br>
 'Acct_007': 'Land and Building',</br>
 'Acct_008': 'Other Fixed Assets',</br>
 'Acct_009': 'Other Assets',</br>
 'Acct_009A': 'Other Assets, Accrued Interest on Loans',</br>
 'Acct_009B': 'Other Assets, Accrued Interest on Investments',</br>
 'Acct_009C': 'Other Assets, All Other',</br>
 'Acct_009D': 'Total Intangible Assets,'</br>
 'Acct_009D1': 'Identifiable Intangible Assets',</br>
 'Acct_009D2': 'Goodwill',</br>
 'Acct_009E': 'Non-Trading Derivative Assets',</br>
 'Acct_010': 'TOTAL ASSETS'}...etc</br>

# Create a Mapping of Accounts and Their Descriptions From The Description Files

In [212]:
acct_detailed_desc = acct_description.set_index('Account')['AcctDesc'].dropna().to_dict()

{'Acct_001': 'Include the dollar amount of outstanding loans involving repossession of collateral, any note or contract receivable resulting from the sale of assets acquired in the liquidation of loans and loans to non-members.',</br>

 'Acct_002': 'Leases Receivable. Include the rate, number, and dollar amount of outstanding direct financing leases as defined by GAAP (credit union is lessor). Credit unions that lease personal property such as vehicles to members make direct financing leases.',</br>
 
 'Acct_003': 'Loans Held for Sale. Report the amount of outstanding loans either identified for sale at origination or subsequently for which there has been a decision to sell. Loans held for Sale should not be included in the amounts reported under the Loan & Leases section lines 15 through 22.',</br>
 
 'Acct_007': 'Land and building, less depreciation on building, if any.',</br>
 
 'Acct_008': 'All other fixed assets such as furniture and fixtures, and leasehold improvements, less related depreciation, if any.  In addition, include leased assets under capital lease (credit union is lessee), less accumulated depreciation, if any.  In this situation, the credit union is leasing assets and granted a lease from an outside entity.',</br>
 
 'Acct_009': 'Include prepaid expenses, accounts receivable, accrued income on loans and investments, etc.  In addition, include direct financing leases, (credit union is lessor).  Credit unions that lease personal property such as vehicles to members make direct financing leases.  In this situation, the credit union is granting a lease to the member.',</br>
 
 'Acct_009A': 'Other Assets, Accrued Interest on Loans.',</br>
 
 'Acct_009B': 'Other Assets, Accrued Interest on Investments.',</br>
 
 'Acct_009C': 'Other Assets, All Other.',</br>
 
 'Acct_009D': 'Total Intangible Assets',</br>
 
 'Acct_009D1': 'Identifiable Intangible Assets',</br>
 
 'Acct_009D2': 'Goodwill',</br>
 
 'Acct_009E': 'Non-Trading Derivative Assets',</br>
 
 'Acct_010': 'TOTAL ASSETS'}..ect</br>

# Load FS220 Files

In [213]:
log = logging.getLogger(__name__)

def _read_txt_with_enc_fallback(path: Path) -> pd.DataFrame:
    """Try UTF-8, then cp1252, then latin1."""
    for enc in ("utf-8", "cp1252", "latin1"):
        try:
            df = pd.read_csv(path, encoding=enc)  
            log.info("Loaded %s (encoding=%s, shape=%s)", path.name, enc, df.shape)
            return df
        except UnicodeDecodeError:
            continue
    # last resort: replace bad bytes
    df = pd.read_csv(path, encoding="utf-8", encoding_errors="replace")
    log.info("Loaded %s (encoding=utf-8 with replacement, shape=%s)", path.name, df.shape)
    return df

def load_fs220_files(
    data_dir: str | Path,
    subfolder: str | Path,
    base_name: str = "FS220",
    suffixes: list[str] | None = None,
) -> dict[str, pd.DataFrame]:
    """
    Load FS220*.txt files into a dict of DataFrames.

    Returns a dict mapping variable-like names to DataFrames, e.g.:
      {'fs220': df, 'fs220_a': dfA, ...}
    """
    root = Path(data_dir) / subfolder
    suffixes = [""] if not suffixes else suffixes

    out: dict[str, pd.DataFrame] = {}
    for suf in suffixes:
        filename = f"{base_name}{suf}.txt" if suf else f"{base_name}.txt"
        path = root / filename
        name = (f"{base_name.lower()}_{suf.lower()}" if suf else base_name.lower())

        if not path.exists():
            log.warning("File not found: %s", path)
            continue

        try:
            out[name] = _read_txt_with_enc_fallback(path)
        except Exception as e:
            log.error("Failed to load %s: %s", path, e)
            continue

    return out

In [214]:
SUBFOLDER = "call-report-data-2024-03" # March
SUFFIXES = ["", "A", "B", "C", "D", "G", "H", "I", "J", "K", "L", "M", "N", "P", "Q", "R", "S"]

fs220_dataframes = load_fs220_files(DATA_DIR, SUBFOLDER, base_name="FS220", suffixes=SUFFIXES)

INFO:__main__:Loaded FS220.txt (encoding=utf-8, shape=(4670, 246))
INFO:__main__:Loaded FS220A.txt (encoding=utf-8, shape=(4670, 249))
INFO:__main__:Loaded FS220B.txt (encoding=utf-8, shape=(4670, 250))
INFO:__main__:Loaded FS220C.txt (encoding=utf-8, shape=(4670, 250))
INFO:__main__:Loaded FS220D.txt (encoding=cp1252, shape=(4670, 230))
INFO:__main__:Loaded FS220G.txt (encoding=utf-8, shape=(4670, 252))
INFO:__main__:Loaded FS220H.txt (encoding=utf-8, shape=(4670, 249))
INFO:__main__:Loaded FS220I.txt (encoding=utf-8, shape=(4670, 251))
INFO:__main__:Loaded FS220J.txt (encoding=utf-8, shape=(4670, 255))
INFO:__main__:Loaded FS220K.txt (encoding=utf-8, shape=(4670, 148))
INFO:__main__:Loaded FS220L.txt (encoding=utf-8, shape=(4670, 243))
INFO:__main__:Loaded FS220M.txt (encoding=utf-8, shape=(4670, 70))
INFO:__main__:Loaded FS220N.txt (encoding=utf-8, shape=(4670, 81))
INFO:__main__:Loaded FS220P.txt (encoding=utf-8, shape=(4670, 193))
INFO:__main__:Loaded FS220Q.txt (encoding=utf-8, shape=(4670, 203))
INFO:__main__:Loaded FS220R.txt (encoding=utf-8, shape=(4670, 231))
INFO:__main__:Loaded FS220S.txt (encoding=utf-8, shape=(4670, 30))

In [215]:
FS220 = fs220_dataframes['fs220']
FS220_a = fs220_dataframes['fs220_a']
FS220_b = fs220_dataframes['fs220_b']
FS220_c = fs220_dataframes['fs220_c']
FS220_d = fs220_dataframes['fs220_d']
FS220_g = fs220_dataframes['fs220_g']
FS220_h = fs220_dataframes['fs220_h']
FS220_i = fs220_dataframes['fs220_i']
FS220_j = fs220_dataframes['fs220_j']
FS220_k = fs220_dataframes['fs220_k']
FS220_l = fs220_dataframes['fs220_l']
FS220_m = fs220_dataframes['fs220_m']
FS220_n = fs220_dataframes['fs220_n']
FS220_p = fs220_dataframes['fs220_p']
FS220_q = fs220_dataframes['fs220_q']
FS220_r = fs220_dataframes['fs220_r']
FS220_s = fs220_dataframes['fs220_s']

In [216]:
df_list = [
    FS220, FS220_a, FS220_b, FS220_c, FS220_d, FS220_g, FS220_h,
    FS220_i, FS220_j, FS220_k, FS220_l, FS220_m, FS220_n,
    FS220_p, FS220_q, FS220_r, FS220_s
]

for i, df in enumerate(df_list):
    if "CYCLE_DATE" in df.columns:
        print(f"DataFrame {i} contains Cycle_Date")
    else:
        print(f"DataFrame {i} does NOT contain Cycle_Date")

DataFrame 0 contains Cycle_Date
DataFrame 1 contains Cycle_Date
DataFrame 2 contains Cycle_Date
DataFrame 3 contains Cycle_Date
DataFrame 4 contains Cycle_Date
DataFrame 5 contains Cycle_Date
DataFrame 6 contains Cycle_Date
DataFrame 7 contains Cycle_Date
DataFrame 8 contains Cycle_Date
DataFrame 9 contains Cycle_Date
DataFrame 10 contains Cycle_Date
DataFrame 11 contains Cycle_Date
DataFrame 12 contains Cycle_Date
DataFrame 13 does NOT contain Cycle_Date
DataFrame 14 does NOT contain Cycle_Date
DataFrame 15 does NOT contain Cycle_Date
DataFrame 16 contains Cycle_Date

# Normalizing Column Names

In [217]:
def normalize_id_columns(df, targets=("CU_NUMBER","CYCLE_DATE","JOIN_NUMBER")):
    df.columns = [
        c.upper() if c.upper()in targets else c
        for c in df.columns
    ]
    return df

# One Wide File: Rename Columns and Drop Inactive Accounts

In [218]:
def normalize_id_columns(df, targets=("CU_NUMBER","CYCLE_DATE","JOIN_NUMBER")):
    """
    Force just the target ID columns to uppercase (if present), leave others intact.
    """
    targets = set(targets)
    df.columns = [c.upper() if c.upper() in targets else c for c in df.columns]
    return df


def normalize_acct_code_preserve_suffix(x: str, pad: int = 3) -> str | None:
    """
    Normalize to 'ACCT_###<SUFFIX>' where <SUFFIX> is optional letters (e.g., B, AB).
    Examples:
      'Acct_21b'  -> 'ACCT_021B'
      'ACCT-21B'  -> 'ACCT_021B'
      'acct021'   -> 'ACCT_021'
      'Acct 21 a' -> 'ACCT_021A'
    Returns None if no digits are found.
    """
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return None
    s = str(x).strip()

    # grab digits and optional trailing letters (ignore separators/case)
    m = re.search(r'(\d+)\s*([A-Za-z]{1,3})?\s*$', re.sub(r'[^0-9A-Za-z]+', ' ', s))
    if not m:
        return None
    num = m.group(1).zfill(pad)
    suf = (m.group(2) or "").upper()
    return f"ACCT_{num}{suf}"


def normalize_account_columns(df, id_cols=("CU_NUMBER","CYCLE_DATE","JOIN_NUMBER"), pad: int = 3):
    id_set = set(id_cols)
    rename_map = {}
    for c in df.columns:
        if c in id_set:
            continue
        norm = normalize_acct_code_preserve_suffix(c, pad=pad)
        if norm is not None and norm != c:
            rename_map[c] = norm

    # Guard against true collisions (very rare once suffix is preserved)
    vals = list(rename_map.values())
    dup_norms = {v for v in set(vals) if vals.count(v) > 1}
    if dup_norms:
        # Make conflicting ones unique without losing lineage
        k = 1
        for orig, norm in list(rename_map.items()):
            if norm in dup_norms:
                rename_map[orig] = f"{norm}__DUP{k}"
                k += 1

    if rename_map:
        df.rename(columns=rename_map, inplace=True)
    return rename_map

In [219]:
df_list = [
    FS220, FS220_a, FS220_b, FS220_c, FS220_d, FS220_g, FS220_h,
    FS220_i, FS220_j, FS220_k, FS220_l, FS220_m, FS220_n,
    FS220_p, FS220_q, FS220_r, FS220_s
]

# Normalize in-place across the list
id_cols = ("CU_NUMBER","CYCLE_DATE","JOIN_NUMBER")
for i, df in enumerate(df_list, start=1):
    normalize_id_columns(df, targets=id_cols)
    acct_renames = normalize_account_columns(df, id_cols=id_cols, pad=3)

    #print(f"DF {i}: normalized {len(acct_renames)} account columns")

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,UPDATE_DATE,ACCT_007,ACCT_008,ACCT_009,ACCT_010,ACCT_011C,ACCT_013,ACCT_018,ACCT_019,ACCT_021B,ACCT_022B,ACCT_023B,ACCT_025A,ACCT_025B,ACCT_031A,ACCT_031B,ACCT_041B,ACCT_042,ACCT_058C,ACCT_065,ACCT_067,ACCT_068,ACCT_069,ACCT_080,ACCT_083,ACCT_084,ACCT_100,ACCT_300,ACCT_340,ACCT_380,ACCT_386,ACCT_387,ACCT_388,ACCT_392,ACCT_400,ACCT_457,ACCT_521,ACCT_522,ACCT_523,ACCT_524,ACCT_550,ACCT_551,ACCT_552,ACCT_562,ACCT_563,ACCT_602,ACCT_630,...,ACCT_652B,ACCT_652C1,ACCT_652C2,ACCT_652D,ACCT_766A,ACCT_766B,ACCT_766C1,ACCT_766C2,ACCT_766D,ACCT_766E,ACCT_798A1,ACCT_798A2,ACCT_798A3,ACCT_009A,ACCT_009B,ACCT_009C,ACCT_769A1,ACCT_769B1,ACCT_616,ACCT_616A,ACCT_704A1,ACCT_704C1,ACCT_980,ACCT_742C1,ACCT_742C2,ACCT_020J,ACCT_020K,ACCT_020L,ACCT_021J,ACCT_021K,ACCT_021L,ACCT_022J,ACCT_022K,ACCT_022L,ACCT_023J,ACCT_023K,ACCT_023L,ACCT_041J,ACCT_041K,ACCT_041L,Acct_1019,Acct_1019A,Acct_1019B,Acct_1019C,Acct_1019D,Acct_1019E,Acct_789A,Acct_789A1,Acct_789B,Acct_789B1
0,1,3/31/2024 0:00:00,2,4/29/2024 10:20:52 PM,42402,7458,0,11182372,0,9856392,9856392,0,46439,478,0,767,8953804,31,720671,69523,0,0,0,0,0,0,0,1276,2000,0,0,0,32327,0,0,0,0,0,0,0.0,925.0,674.0,674.0,6519,696,0,0,0,29922,88074,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3939,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,4/30/2024 10:18:47 PM,2926739,1436871,0,275381898,0,208672795,241409795,0,1111383,826955,93026,20300,194154396,1090,14248221,2720931,0,0,0,0,0,0,0,28945,70000,0,0,112,788080,0,0,0,0,0,32737,1074.0,1184.0,500.0,666.0,367890,115903,0,0,0,0,275698,...,0,0,0,0,0,0,0,0,0,0,0,0,0,766577,65767,9054849,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,4/18/2024 10:06:42 PM,5004004,555306,0,61526262,0,56663797,56663797,0,152053,2677,0,8001,27050615,609,2777539,247781,0,0,0,0,0,0,0,9133,19133,0,0,15588,85617,0,0,0,0,0,0,1243.0,1050.0,800.0,875.0,206482,30395,0,0,0,0,379808,...,0,0,0,0,0,0,0,0,0,0,0,0,0,71417,53884,3270816,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,4/25/2024 10:08:35 PM,12889552,665915,0,1058083728,0,842713968,919926247,0,849774,962009,0,35885,933368458,7449,99199184,2662923,0,0,0,0,0,0,0,65941,849530,0,0,542312,6944265,0,0,0,0,0,22,950.0,950.0,364.0,364.0,769471,201614,0,0,0,0,234783,...,0,0,0,0,0,0,0,0,0,0,0,0,0,3457830,144902,5919469,0,0,0,0,0,27026668,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,5/14/2024 10:02:56 PM,0,1893,0,9656630,0,8380331,8380331,0,0,529,16340,280,3901475,14,239962,16869,0,0,0,0,0,0,0,900,1320,0,0,45,10053,0,0,0,0,0,0,1490.0,850.0,624.0,699.0,21311,183,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,5063,15434,25931,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,4/28/2024 10:05:53 PM,0,127724,0,66864410,0,61377062,61377062,0,27701,0,0,88294,44084201,44,2331916,43027,0,0,0,0,0,0,0,2655,3895000,0,0,116,361505,0,0,0,0,0,0,1294.0,1200.0,725.0,850.0,33080,8854,0,0,0,-56864,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,134812,45376,2680037,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,4/17/2024 10:08:32 PM,4170475,274366,0,465896889,0,396173443,396173443,0,278727,226016,0,18482,361792262,832,22302047,773832,0,0,0,0,0,0,0,25883,500000,0,0,189139,1936840,0,0,0,0,0,0,1450.0,1349.0,750.0,860.0,361335,117940,0,0,0,896288,447680,...,0,0,0,0,0,0,0,0,0,0,0,0,0,1071016,159038,10873708,0,0,0,0,0,852324,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,4/29/2024 10:12:07 PM,15013790,795315,0,383441194,0,348703744,348953744,0,562189,933008,155891,13814,273193111,553,10987820,2169533,0,0,0,0,0,0,0,24762,255994,0,0,0,1520398,0,0,0,0,0,1,1699.0,1324.0,849.0,924.0,356658,47568,0,0,0,277626,7954429,...,0,0,0,0,0,0,0,0,0,0,0,0,0,1027011,175867,11930979,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,5/15/2024 4:37:21 PM,4067996,685430,0,158761538,0,141912799,141912799,0,99699,38370,0,8065,118017639,543,9623913,761214,0,0,0,0,0,0,0,12808,900000,0,0,48533,570310,0,0,0,0,0,0,1263.0,960.0,533.0,689.0,143368,36308,0,0,0,0,215962,...,0,0,0,0,0,0,0,0,0,0,0,0,0,732176,67814,3088673,0,0,0,0,0,633121,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,4/25/2024 10:19:51 PM,8117822,483814,0,241976246,0,231297778,231297778,0,199692,38054,0,11363,125457212,329,5299557,548651,0,0,0,0,0,0,0,21360,3600578,0,0,0,712200,0,0,0,0,0,0,833.0,880.0,481.0,492.0,292172,18177,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,357921,225859,12669185,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_001,ACCT_011A,ACCT_011B1,ACCT_011B2,ACCT_013A,ACCT_013B1,ACCT_013B2,ACCT_014,ACCT_017,ACCT_018A,ACCT_018B1,ACCT_018B2,ACCT_021A,ACCT_022A,ACCT_023A,ACCT_041A,ACCT_058A,ACCT_058B1,ACCT_058B2,ACCT_062,ACCT_063,ACCT_076,ACCT_077,ACCT_078,ACCT_079,ACCT_081,ACCT_082,ACCT_090,ACCT_099,ACCT_110,ACCT_119,ACCT_120,ACCT_124,ACCT_125A,ACCT_125B,ACCT_125C,ACCT_125D,ACCT_125E,ACCT_126A,ACCT_126B,ACCT_126C,ACCT_126D,ACCT_126E,ACCT_131,ACCT_132,ACCT_133,ACCT_134,...,ACCT_714A,ACCT_715A,ACCT_716A,ACCT_020E,ACCT_021E,ACCT_022E,ACCT_023E,ACCT_041E,ACCT_020F,ACCT_021F,ACCT_022F,ACCT_023F,ACCT_041F,ACCT_065A,ACCT_065B,ACCT_065C,ACCT_065D,ACCT_065E,ACCT_067A,ACCT_067B,ACCT_067C,ACCT_550J,ACCT_550K,ACCT_550L,ACCT_551J,ACCT_551K,ACCT_551L,ACCT_029A,ACCT_029B,ACCT_029C,ACCT_029D,ACCT_029E,ACCT_030A,ACCT_030B,ACCT_030C,ACCT_030D,ACCT_030E,ACCT_032A,ACCT_032B,ACCT_032C,ACCT_032D,ACCT_032E,ACCT_704F1,ACCT_704F2,ACCT_704F3,ACCT_704F4,ACCT_811B,ACCT_PP0027,ACCT_PP0029,ACCT_PP0031
0,1,3/31/2024 0:00:00,2,0,0,0,0,7796617,2059775,0,11182372,0,7796617,2059775,0,0,0,0,8,0,0,0,0,122023,2,0,0,0,0,0,0,0,134025,0,12879,0,0,0,0,0,0,0,0,0,0,0,6812,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,200765794,6941260,965741,275381898,0,202748794,9620260,29040741,0,0,0,269,0,0,0,0,122023,2,0,0,0,0,0,0,0,3416745,0,359245,0,0,0,0,0,0,0,0,0,0,0,370345,0,0,0,...,0,0,0,0,0,0,0,117516,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,55486886,911636,265274,61526262,0,55486886,911636,265274,0,0,0,113,0,0,0,0,32023,2,0,0,0,0,0,0,0,666667,0,142957,0,0,0,0,0,0,0,0,0,0,0,321880,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,561207454,110456857,171049658,1058083728,0,566286732,157197857,196441658,0,0,0,117,0,0,0,0,122023,2,0,0,0,0,0,0,0,12254211,0,1058966,0,0,0,0,0,0,0,0,0,0,0,1345025,0,0,0,...,0,0,0,0,0,0,0,1594875,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,8380329,0,0,9656630,0,8380329,0,0,0,0,0,2,0,0,0,0,22024,2,0,0,0,0,0,0,0,53295,0,40363,0,0,0,0,0,0,0,0,0,0,0,6993,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,37501164,20303058,3572840,66864410,0,37501164,20303058,3572840,0,0,0,165,0,0,0,0,32023,3,0,0,0,0,0,0,0,553941,0,124663,0,0,0,0,0,0,0,0,0,0,0,11871,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,365686217,17162114,13325112,465896889,0,365686217,17162114,13325112,0,0,0,63,0,0,0,0,122023,3,0,0,0,0,0,0,0,4850503,0,777426,0,0,0,0,0,0,0,0,0,0,0,606380,0,0,0,...,0,0,0,0,0,0,0,470168,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,330078653,13144301,5480790,383441194,0,330328653,13144301,5480790,0,0,0,99,0,0,0,0,122023,2,0,0,0,0,0,0,0,3831447,0,646995,0,0,0,0,0,0,0,0,0,0,0,460252,0,0,0,...,0,0,0,0,0,0,0,819457,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,135382132,4101773,2428894,158761538,0,135382132,4101773,2428894,0,0,0,65,0,0,0,0,122023,2,0,0,0,0,0,0,0,1775653,0,271232,0,0,0,0,0,0,0,0,0,0,0,283893,0,0,0,...,0,0,0,0,0,0,0,99608,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,217937828,9876590,3483360,241976246,0,217937828,9876590,3483360,0,0,0,54,0,0,0,0,32023,2,0,0,0,0,0,0,0,1680917,0,464896,0,0,0,0,0,0,0,0,0,0,0,727264,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_606A,ACCT_606B,ACCT_607,ACCT_608,ACCT_609,ACCT_620,ACCT_621,ACCT_622,ACCT_623,ACCT_624,ACCT_625,ACCT_626,ACCT_627,ACCT_628,ACCT_630A,ACCT_630B1,ACCT_630B2,ACCT_640,ACCT_652C,ACCT_653A,ACCT_653B1,ACCT_653B2,ACCT_653C,ACCT_655C,ACCT_656A,ACCT_656B1,ACCT_656B2,ACCT_657A,ACCT_657B1,ACCT_657B2,ACCT_659,ACCT_660,ACCT_661,ACCT_670A,ACCT_670B,ACCT_672C,ACCT_698,ACCT_709,ACCT_725,ACCT_726,ACCT_731,ACCT_732,ACCT_733,ACCT_734,ACCT_735,ACCT_736,ACCT_737,...,Acct_680,Acct_681,Acct_682,Acct_769,Acct_785,Acct_786,Acct_787,Acct_892,Acct_895,Acct_896,Acct_899,ACCT_020I,ACCT_021I,ACCT_022I,ACCT_023I,ACCT_041I,ACCT_550I,ACCT_551I,ACCT_981,ACCT_981A,ACCT_981B,ACCT_065A1,ACCT_065A2,ACCT_065A3,ACCT_065A4,ACCT_065B1,ACCT_065C1,ACCT_065D1,ACCT_065E1,ACCT_067A1,ACCT_067A2,ACCT_067B1,ACCT_067C1,ACCT_068A,ACCT_069A,ACCT_033A,ACCT_033B,ACCT_033C,ACCT_033D,ACCT_033E,ACCT_034A,ACCT_034B,ACCT_034C,ACCT_034D,ACCT_034E,ACCT_035A,ACCT_035B,ACCT_035C,ACCT_035D,ACCT_035E
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,88074,0,0,0,0,0,0,0,0,0,0,0,0,6715796,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9856392,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,275698,0,0,0,0,0,0,0,0,0,0,0,0,121112510,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,91133,13999,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3415824,0,0,0,0,0,0,0,0,3415824,237993971,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,379808,0,0,0,0,0,0,0,0,0,0,0,0,26235674,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,31364,11422,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,552692,0,0,0,0,0,0,0,0,552692,56111105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,234783,0,0,0,0,0,0,0,0,0,0,0,0,172985942,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,82858,18803,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,88547728,0,0,0,0,0,0,0,0,88547728,831378519,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4977160,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8380331,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18904383,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,447680,0,0,0,0,0,0,0,0,0,0,0,0,113933357,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,70603,6265,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7954429,0,0,0,0,0,0,0,0,0,0,0,0,66089346,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,160000,0,...,26143,5701,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,215962,0,0,0,0,0,0,0,0,0,0,0,0,53203424,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,499528,0,...,24194,2486,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100572837,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,56320,5994,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_831A,ACCT_831B,ACCT_831C,ACCT_831D,ACCT_831E,ACCT_831F,ACCT_831G,ACCT_831H,ACCT_831I,ACCT_831J,ACCT_832A,ACCT_832B,ACCT_832C,ACCT_832D,ACCT_832E,ACCT_832F,ACCT_832G,ACCT_832H,ACCT_832I,ACCT_832J,ACCT_833A,ACCT_833B,ACCT_833C,ACCT_833D,ACCT_833E,ACCT_833F,ACCT_833G,ACCT_833H,ACCT_833I,ACCT_833J,ACCT_834A,ACCT_834B,ACCT_834C,ACCT_834D,ACCT_834E,ACCT_834F,ACCT_834G,ACCT_834H,ACCT_834I,ACCT_834J,ACCT_835A,ACCT_835B,ACCT_835C,ACCT_835D,ACCT_835E,ACCT_835F,ACCT_835G,...,ACCT_551D,ACCT_550E,ACCT_551E,ACCT_550F,ACCT_551F,ACCT_550G,ACCT_551G,ACCT_550H,ACCT_551H,ACCT_818A,ACCT_631,ACCT_632,ACCT_633,ACCT_634,ACCT_635,ACCT_636,ACCT_637,ACCT_638,ACCT_639,ACCT_641,ACCT_1000A,ACCT_1000B,ACCT_1000C,ACCT_1001A,ACCT_1001B,ACCT_1001C,ACCT_1002A,ACCT_1002B,ACCT_1002C,ACCT_036A,ACCT_036B,ACCT_036C,ACCT_036D,ACCT_036E,ACCT_037A,ACCT_037B,ACCT_037C,ACCT_037D,ACCT_037E,ACCT_038A,ACCT_038B,ACCT_038C,ACCT_038D,ACCT_038E,ACCT_039A,ACCT_039B,ACCT_039C,ACCT_039D,ACCT_039E,ACCT_642
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,11345,0,11345,576,0,0,0,0,0,0,0,0,0,0,0,0,14983499,1750620,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,567667,0,0,0,0,0,0,0,699866,173375,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,482232,81413,0,0,0,0,0,0,0,0,0,0,0,0,0,0,395849945,60785268,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,317731,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15811152,1977602,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,53548919,10202668,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,75264,395,0,0,0,0,0,0,0,0,0,0,0,0,0,0,52591905,3836486,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,3778,16426,35152,49,0,0,0,0,0,0,0,0,0,0,0,0,15685514,2514769,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27696535,5693308,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,CEO,Fax,Phone,Preparer,President,Principal,ACCT_876,ACCT_830A,ACCT_830B,ACCT_830C,ACCT_830D,ACCT_830E,ACCT_830F,ACCT_830G,ACCT_830H,ACCT_830I,ACCT_830J,CEO_F,CEO_M,Preparer_F,Preparer_M,President_F,President_M,Principal_F,Principal_M,Acct_891,ACCT_893,ACCT_894,Acct_700,Acct_701,Acct_886A,Acct_886B,Acct_886C,Acct_886D,Acct_886E,Acct_886F,Acct_886G,Acct_887A,Acct_887B,Acct_887C,Acct_887D,Acct_887E,Acct_887F,Acct_887G,Acct_887H,Acct_887I,Acct_887J,...,Acct_855K,Acct_855L,Acct_855M,Acct_855N,Acct_855O,Acct_855P,Acct_855Q,Acct_855R,Acct_855S,Acct_855T,BondProvider,MemberMinorityStatus,EligibleMinorityStatus,MemberAsianAmerican,MemberAfricanAmerican,MemberHispanicAmerican,MemberNativeAmerican,EligibleAsianAmerican,EligibleAfricanAmerican,EligibleHispanicAmerican,EligibleNativeAmerican,Acct_887V,Acct_879Q1,Acct_1027Z,Acct_1028Z,Acct_1029Z,ACCT_879B6,ACCT_879B7,ACCT_PI0007,ACCT_PI0008,ACCT_PI0009,ACCT_PP0026,ACCT_PP0028,ACCT_PP0030,ACCT_PP0032,ACCT_PP0033,Acct_879D10,ACCT_PC0013,ACCT_PI0011,ACCT_PI0012,ACCT_PI0013,ACCT_PI0014,ACCT_PI0015,ACCT_PI0016,ACCT_PI0017,ACCT_PI0018,ACCT_PP0034,ACCT_PP0035,ACCT_PP0036,ACCT_PP0058
0,1,3/31/2024 0:00:00,2,PRICE,9.037943e+09,9037983918,PRICE,MARTIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,JENNIFER,NaN,JENNIFER,NaN,PAUL,T,NaN,NaN,http://www.morrissheppardfcu.org,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,...,,,,,,,,,,,CUMIS,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,NaN,0,0,0,0,0,1,1,0,0,0,NaN,NaN,0
1,6,3/31/2024 0:00:00,7,DeLucca,5.048899e+09,5048899090,Hudson,Jurisich III,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Judy,S,Lisa,NaN,Joseph,J,NaN,NaN,http://www.noffcu.org,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,...,,,,,,,,,,,CUMIS,1,0,1,1,1,0,0,0,0,0,0,0,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,0,1.0,0,1,0,0,0,1,0,1,0,1,CULIANCE,CO-OP Shared Branching,1
2,12,3/31/2024 0:00:00,11,Althen,NaN,8602964379,Althen,Krikorian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Deborah,A,Deborah,NaN,David,A,NaN,NaN,http://www.franklintrust.org,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,1,...,,,,,,,,,,,Other,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,1.0,0,1,0,0,0,0,1,0,0,1,Co-op,Co-op,1
3,13,3/31/2024 0:00:00,12,Kuslikis,2.252147e+09,2252146800,Myers,Langlois,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tom,NaN,Rick,NaN,Darrell,NaN,NaN,NaN,http://www.efcufinancial.org,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,1,...,,,,,,,,,,,CUMIS,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,NaN,0,1,0,1,0,1,0,1,0,1,Allpoint,CO-OP,1
4,16,3/31/2024 0:00:00,14,Steinberg,4.024498e+09,4022717285,Hill,Benham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clayton,M,Melissa,NaN,Michelle,R,NaN,NaN,http://WWW.WOODMENFCU.ORG,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,...,,,,,,,,,,,CUMIS,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,NaN,0,1,0,0,0,1,1,0,0,1,AllPoint,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,Garcia,8.476471e+09,8476471030,Sullivan,Abinion,NaN,ASI/ESI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jose,NaN,Joseph,NaN,Emir,NaN,NaN,NaN,http://www.nwccu.com,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,1,...,,,,,,,,,,,CUMIS,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,NaN,0,1,0,0,0,0,0,0,0,1,CUliance,Co-Op,1
4666,97109,3/31/2024 0:00:00,2759,Bowen,NaN,9378596260,Spivey,Gorman,NaN,Excess Share Insurance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,John,E,Lee,NaN,Daniel,J,NaN,NaN,https://www.rivervalleycu.org,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,1,...,,,,,,,,,,,CUMIS,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,1,1,1,1,1,0,0,0,0,0,NaN,0,1,1,0,0,0,0,0,1,1,Alliance One,Shared Branching through Coop,1
4667,97110,3/31/2024 0:00:00,17502,Sendon,4.064471e+09,4064492680,Halferty,Bouchard,NaN,American Share Insurance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stephen,NaN,Diane,NaN,Kristin,NaN,NaN,NaN,http://www.rmcu.net,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,1,...,,,,,,,,,,,Other,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,NaN,0,1,0,0,0,0,0,0,1,1,"Coop, Moneypass",Coop Shared Branching,1
4668,97111,3/31/2024 0:00:00,21049,Pielemeier,9.378988e+09,9378987800,Puthoff,Thein,NaN,ASI ESI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dean,A,Teri,NaN,Michael,A,NaN,NaN,http://www.abbeycu.com,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,1,...,,,,,,,,,,,Other,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,NaN,0,1,0,0,0,0,0,1,0,1,Alliance One and MoneyPass,Shared branching thru Co-op,1
4669,97112,3/31/2024 0:00:00,22698,Kearney,2.814490e+09,2814490109,PAREDEZ,Paraschos,NaN,American Share Insurance Corp.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Keith,L,RENE,NaN,Catherine,NaN,NaN,NaN,http://www.investexcu.org,NaN,NaN,Well Capitalized,Well Capitalized,0,0,0,0,0,0,0,1,1,0,0,1,1,0,0,0,1,...,,,,,,,,,,,CUMIS,0,0,0,0,0,0,0,0,0,0,1,0,NaN,NaN,NaN,0,0,1,1,1,0,0,0,0,0,NaN,0,1,0,0,0,1,0,1,0,0,NaN,NaN,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_009D,ACCT_009D1,ACCT_009D2,ACCT_020M,ACCT_020N,ACCT_020P,ACCT_020Q,ACCT_021M,ACCT_021N,ACCT_021P,ACCT_021Q,ACCT_022M,ACCT_022N,ACCT_022P,ACCT_022Q,ACCT_023M,ACCT_023N,ACCT_023P,ACCT_023Q,ACCT_041M,ACCT_041N,ACCT_041P,ACCT_041Q,ACCT_1003,ACCT_1004,ACCT_1004A,ACCT_1004B,ACCT_311,ACCT_431,ACCT_550M,ACCT_550N,ACCT_550P,ACCT_550Q,ACCT_551M,ACCT_551N,ACCT_551P,ACCT_551Q,ACCT_619A1,ACCT_619A2,ACCT_619A3,ACCT_619B,ACCT_619B1,ACCT_619B2,ACCT_658A,ACCT_660A,ACCT_690A1,ACCT_690A2,...,ACCT_847T,ACCT_848A,ACCT_848B,ACCT_848C,ACCT_848D,ACCT_848E,ACCT_848F,ACCT_848G,ACCT_848H,ACCT_848I,ACCT_848J,ACCT_848K,ACCT_848L,ACCT_848M,ACCT_848N,ACCT_848O,ACCT_848P,ACCT_848Q,ACCT_848R,ACCT_848S,ACCT_848T,ACCT_849A,ACCT_849B,ACCT_849C,ACCT_849D,ACCT_849E,ACCT_849F,ACCT_849G,ACCT_849H,ACCT_849I,ACCT_849J,ACCT_849K,ACCT_849L,ACCT_849M,ACCT_849N,ACCT_849O,ACCT_849P,ACCT_849Q,ACCT_849R,ACCT_849S,ACCT_849T,ACCT_851,ACCT_852,ACCT_853,ACCT_945C,ACCT_704G1,ACCT_704G2,ACCT_704G3,ACCT_704G4,ACCT_811C
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,290416,290416,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,290416,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,301958,0,100000,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,350141,0,350141,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,89066,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25000,0,25000,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4631222,4631222,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6176000,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2692587,0,207500,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3018313,3018313,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3018313,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1049813,0,100000,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,42444,0,33122,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_020R,ACCT_020S,ACCT_021R,ACCT_021S,ACCT_022R,ACCT_022S,ACCT_023R,ACCT_023S,ACCT_041R,ACCT_041S,ACCT_051A,ACCT_051B,ACCT_051C,ACCT_051D,ACCT_051E,ACCT_052A,ACCT_052B,ACCT_052C,ACCT_052D,ACCT_052E,ACCT_1000D,ACCT_1000E,ACCT_1001D,ACCT_1001E,ACCT_1002D,ACCT_1002E,ACCT_550R,ACCT_550S,ACCT_551R,ACCT_551S,ACCT_816A,ACCT_981C,Acct_031C,Acct_031D,Acct_089A,Acct_089B,Acct_127A,Acct_127B,Acct_128A,Acct_128B,Acct_129A,Acct_129B,Acct_130A,Acct_130B,Acct_136,Acct_137,Acct_310A,...,Acct_854L,Acct_854M,Acct_854N,Acct_854O,Acct_854P,Acct_854Q,Acct_854R,Acct_854S,Acct_854T,Acct_900C1,Acct_900C2,Acct_900C3,Acct_900C4,Acct_900G,Acct_900G1,Acct_900H,Acct_900H1,Acct_900J,Acct_900J1,Acct_900K,Acct_900K1,Acct_900L,Acct_900L1,Acct_900T,Acct_961A1,Acct_961A2,Acct_961A3,Acct_961A4,Acct_963A,Acct_925A1,Acct_925A2,Acct_1004C,Acct_1016,Acct_1016A,Acct_1016B,Acct_1016C,Acct_1016D,Acct_1016E,Acct_1017,Acct_1017A,Acct_1017B,Acct_1017C,Acct_1017D,Acct_1017E,Acct_1018,Acct_1018A,Acct_1018B,Acct_1018C,Acct_1018D,Acct_1018E
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,39918643,0,9,5000,0,614,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2312,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2470771,0,6,11500,0,0,0,0,0,0,0,0,2,2070,0,370,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,111880780,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,445176,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5259941,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,53744282,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,51902523,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21332341,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22383710,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_054A,ACCT_054B,ACCT_054C,ACCT_054D,ACCT_054E,ACCT_055A,ACCT_055B,ACCT_055C,ACCT_055D,ACCT_055E,ACCT_056A,ACCT_056B,ACCT_056C,ACCT_056D,ACCT_056E,ACCT_057A,ACCT_057B,ACCT_057C,ACCT_057D,ACCT_057E,ACCT_059A,ACCT_059B,ACCT_059C,ACCT_059D,ACCT_059E,ACCT_020U,ACCT_021U,ACCT_022U,ACCT_023U,ACCT_041U,ACCT_020V,ACCT_021V,ACCT_022V,ACCT_023V,ACCT_041V,ACCT_020W,ACCT_021W,ACCT_022W,ACCT_023W,ACCT_041W,ACCT_020X,ACCT_021X,ACCT_022X,ACCT_023X,ACCT_041X,ACCT_020Y,ACCT_021Y,...,Acct_814E2,Acct_814J1,Acct_814J2,Acct_814J,Acct_816E1,Acct_816E2,Acct_884A1,Acct_884A2,Acct_884C1,Acct_884C2,Acct_884C,Acct_884D1,Acct_884D2,Acct_884D,Acct_884E,Acct_885C,Acct_885D,Acct_885A1,Acct_885B1,Acct_885C1,Acct_885D1,Acct_885A2,Acct_885B2,Acct_885C2,Acct_885D2,Acct_885A3,Acct_885B3,Acct_885C3,Acct_885D3,Acct_885B4,Acct_885C4,Acct_885D4,Acct_885C5,Acct_885D5,Acct_885A4,Acct_885B5,Acct_885C6,Acct_885D6,Acct_1014,Acct_1014A,Acct_1014B,Acct_1014C,Acct_1014D,Acct_1014E,Acct_1015,Acct_1015A,Acct_1015B,Acct_1015C,Acct_1015D,Acct_1015E
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,7000000,0,0,0,0,0,0,0,7000000,0,0,0,0,0,0,0,0,0,0,0,0,7000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,10000000,0,0,5000000,0,0,0,10000000,0,0,0,5000000,0,0,0,30000000,0,0,0,0,0,0,0,0,45000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22008547,0,0,0,0,0,0,0,0,22008547,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7000000,0,0,0,0,0,0,0,0,7000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,38359536,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_009E,ACCT_825A,ACCT_420D,ACCT_421,ACCT_784A,ACCT_789C,ACCT_789D,ACCT_789E,ACCT_789E1,ACCT_789E2,ACCT_789F,ACCT_789G,ACCT_789H,ACCT_1020,ACCT_1021,ACCT_1022,ACCT_1023,ACCT_1024,ACCT_1025,ACCT_1025E,ACCT_1025H,ACCT_1025L,ACCT_1025N,ACCT_1025P,ACCT_1020A,ACCT_1021A,ACCT_1022A,ACCT_1023A,ACCT_1024A,ACCT_1025A,ACCT_1026A,ACCT_1027A,ACCT_1028A,ACCT_1029A,ACCT_1030A,ACCT_1020B,ACCT_1021B,ACCT_1022B,ACCT_1023B,ACCT_1024B,ACCT_1025B,ACCT_1026B,ACCT_1027B,ACCT_1028B,ACCT_1029B,ACCT_1030B,ACCT_1020C,...,ACCT_1022S,ACCT_1023S,ACCT_1024S,ACCT_1025S,ACCT_1026S,ACCT_1027S,ACCT_1028S,ACCT_1029S,ACCT_1030S,ACCT_1020T,ACCT_1021T,ACCT_1022T,ACCT_1023T,ACCT_1024T,ACCT_1028T,ACCT_1028U,ACCT_1028V,ACCT_1028W,ACCT_1028X,ACCT_1029,ACCT_1020U,ACCT_1021U,ACCT_1022U,ACCT_1023U,ACCT_1024U,ACCT_1029E,ACCT_1029H,ACCT_1029L,ACCT_1029N,ACCT_1029P,ACCT_1020V,ACCT_1021V,ACCT_1022V,ACCT_1023V,ACCT_1024V,ACCT_1029T,ACCT_1029U,ACCT_1029V,ACCT_1029W,ACCT_1029X,ACCT_1020W,ACCT_1021W,ACCT_1022W,ACCT_1023W,ACCT_1024W,ACCT_1030,ACCT_1030E,ACCT_1030H,ACCT_1030L,ACCT_1030N
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,3483022,3925642,0,0,7408664,703577,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,800000,0,0,0,800000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,871370,871370,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,6083609,0,0,0,6083609,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,2410599,0,2639997,0,0,0,5050596,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,1059987,0,0,7257699,8317686,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_1020X,ACCT_1021X,ACCT_1022X,ACCT_1023X,ACCT_1024X,ACCT_1030P,ACCT_1030T,ACCT_1030U,ACCT_1030V,ACCT_1030W,ACCT_1030X,ACCT_1020Y,ACCT_1021Y,ACCT_1022Y,ACCT_1023Y,ACCT_1024Y,ACCT_1025Y,ACCT_1026Y,ACCT_1027Y,ACCT_1028Y,ACCT_1029Y,ACCT_1030Y,ACCT_1020S1,ACCT_1021S1,ACCT_1022S1,ACCT_1023S1,ACCT_1024S1,ACCT_1025S1,ACCT_1026S1,ACCT_1027S1,ACCT_1028S1,ACCT_1029S1,ACCT_1030S1,ACCT_1020T1,ACCT_1021T1,ACCT_1022T1,ACCT_1023T1,ACCT_1024T1,ACCT_1025T1,ACCT_1026T1,ACCT_1027T1,ACCT_1028T1,ACCT_1029T1,ACCT_1030T1,ACCT_1020U1,ACCT_1021U1,ACCT_1022U1,...,ACCT_1041A,ACCT_1031B,ACCT_1032B,ACCT_1033B,ACCT_1034B,ACCT_1035B,ACCT_1036B,ACCT_1037B,ACCT_1038B,ACCT_1039B,ACCT_1040B,ACCT_1041B,ACCT_1031C,ACCT_1032C,ACCT_1033C,ACCT_1034C,ACCT_1035C,ACCT_1036C,ACCT_1037C,ACCT_1038C,ACCT_1039C,ACCT_1040C,ACCT_1041C,ACCT_1031D,ACCT_1032D,ACCT_1033D,ACCT_1034D,ACCT_1035D,ACCT_1036D,ACCT_1037D,ACCT_1038D,ACCT_1039D,ACCT_1040D,ACCT_1041D,ACCT_1031,ACCT_1032,ACCT_1033,ACCT_1034,ACCT_1035,ACCT_1036,ACCT_1037,ACCT_1038,ACCT_1039,ACCT_1040,ACCT_1041,ACCT_1042A,ACCT_1042,ACCT_1042B,ACCT_1042C,ACCT_1042D
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_020G3,ACCT_020G4,ACCT_020H1,ACCT_020N1,ACCT_020P3,ACCT_020P4,ACCT_020Q1,ACCT_020W1,ACCT_020Y1,ACCT_021G3,ACCT_021G4,ACCT_021H1,ACCT_021N1,ACCT_021P3,ACCT_021P4,ACCT_021Q1,ACCT_021W1,ACCT_021Y1,ACCT_022G3,ACCT_022G4,ACCT_022H1,ACCT_022N1,ACCT_022P3,ACCT_022P4,ACCT_022Q1,ACCT_022W1,ACCT_022Y1,ACCT_023G3,ACCT_023G4,ACCT_023H1,ACCT_023N1,ACCT_023P3,ACCT_023P4,ACCT_023Q1,ACCT_023W1,ACCT_023Y1,ACCT_025A1,ACCT_025B1,ACCT_040A1,ACCT_040B2,ACCT_040C1,ACCT_040D1,ACCT_040E1,ACCT_041G3,ACCT_041G4,ACCT_041H1,ACCT_041N1,...,ACCT_475K2,ACCT_475K3,ACCT_475L2,ACCT_475L3,ACCT_475M,ACCT_475M1,ACCT_525,ACCT_526,ACCT_550G3,ACCT_550G4,ACCT_550H1,ACCT_550N1,ACCT_550P3,ACCT_550P4,ACCT_550Q1,ACCT_550W1,ACCT_550Y1,ACCT_551G3,ACCT_551G4,ACCT_551H1,ACCT_551N1,ACCT_551P3,ACCT_551P4,ACCT_551Q1,ACCT_551W1,ACCT_551Y1,ACCT_562A,ACCT_562B,ACCT_563A,ACCT_595B,ACCT_691B1,ACCT_691C1,ACCT_691C2,ACCT_691K8,ACCT_691K9,ACCT_691L8,ACCT_691L9,ACCT_691M8,ACCT_691M9,ACCT_691N8,ACCT_691N9,ACCT_691P,ACCT_691P1,ACCT_691P2,ACCT_698C,ACCT_703A,ACCT_704A2,ACCT_718A3,ACCT_718A4,ACCT_718A5
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,767,8953804,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,674.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2245815,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20300,194154396,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,477.0,655.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,526.0,0.0,827.0,612.0,0,0,0,0,0,0,896370,0,0,0,0,0,0,0,13348302,23727774,0,231467,896370,1127837
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8001,27050615,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,725.0,0.0,725.0,675.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,86334,4130180,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,35885,933368458,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,550.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,850.0,0.0,500.0,250.0,0,0,0,0,0,1108973,0,0,0,0,0,0,0,0,11879743,243836311,10846494,0,1108973,1108973
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,280,3901475,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,850.0,0.0,629.0,699.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,138830,747975,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,88294,44084201,0,0,0,0,0,0,0,0,0,...,0,320357,0,0,0,0,800.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,825.0,0.0,675.0,550.0,0,0,0,0,0,8569196,0,0,0,0,0,0,0,0,862404,21461553,0,0,8569196,8569196
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18482,361792262,0,0,0,0,0,0,0,0,0,...,0,503558,1270469,0,0,0,725.0,750.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,825.0,0.0,725.0,0.0,0,0,0,0,0,8478782,54716,0,0,15166072,0,0,0,0,0,100911200,0,19398840,8533498,27932338
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13814,273193111,0,0,0,0,0,0,0,0,0,...,0,0,30169,0,0,0,726.0,1000.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,950.0,0.0,663.0,700.0,0,0,0,0,0,905005,0,0,0,0,0,0,0,0,31075040,92207244,0,4443810,905005,5348814
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8065,118017639,0,0,0,0,0,0,0,0,0,...,3491323,0,454058,0,0,0,606.0,797.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,823.0,425.0,574.0,760.0,0,0,0,0,0,4547665,0,0,0,1533267,0,0,0,0,7492213,19882133,500000,28323926,3977851,32301777
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,11363,125457212,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,617.0,0.0,445.0,551.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3857281,29325096,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_811B3,ACCT_811B4,ACCT_811B5,ACCT_811C3,ACCT_811C4,ACCT_811C5,ACCT_811D,ACCT_811D1,ACCT_811D2,ACCT_811E,ACCT_811E1,ACCT_811E2,ACCT_812A1,ACCT_812B1,ACCT_812C,ACCT_813A1,ACCT_813A2,ACCT_813B1,ACCT_814A6,ACCT_814A7,ACCT_814A8,ACCT_814J3,ACCT_814J4,ACCT_814J5,ACCT_814K,ACCT_814K1,ACCT_814K2,ACCT_815A1,ACCT_815B1,ACCT_815C,ACCT_816B3,ACCT_816B4,ACCT_816B5,ACCT_816T,ACCT_816T1,ACCT_816T2,ACCT_822A1,ACCT_822B1,ACCT_822C,ACCT_900A1,ACCT_900B1,ACCT_900C5,ACCT_900C6,ACCT_900C7,ACCT_900C8,ACCT_900H2,ACCT_900H3,ACCT_900J2,ACCT_900J3,ACCT_900K2,ACCT_900K3,ACCT_900K4,ACCT_900L2,ACCT_900L3,ACCT_900M,ACCT_900M1,ACCT_900P,ACCT_900T1,ACCT_959A,ACCT_960A,ACCT_960B,ACCT_961A5,ACCT_961A6,ACCT_961A7,ACCT_961A8,ACCT_961A9,ACCT_963C
0,1,3/31/2024 0:00:00,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,165
1,6,3/31/2024 0:00:00,7,0,0,0,0,0,0,2051611,0,0,0,0,0,0,0,32813277,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16891,0,0,4975354,39918643,0,0,0,0,61510,14,2,1,4,0,0,1,2,2,0,3,2,5,6,0,0,0,11,16,188,209,0,0,0,0,0,0,772
2,12,3/31/2024 0:00:00,11,0,0,0,0,0,0,26562,0,0,0,0,0,0,0,2047598,0,0,0,0,0,0,0,0,0,0,0,0,0,0,368868,0,0,0,2470771,0,0,0,0,27743,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,72,81,0,0,0,0,0,0,28
3,13,3/31/2024 0:00:00,12,0,0,0,0,0,0,49642599,0,0,0,0,0,0,0,32541946,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,29429107,111880780,0,0,0,0,267128,0,3,0,0,0,0,0,3,0,0,0,3,3,0,0,0,0,0,3,1708,1334,0,0,0,0,0,0,1039
4,16,3/31/2024 0:00:00,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,404515,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40661,0,0,0,445176,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,10,13,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,0,0,0,0,1117912,0,0,0,0,0,0,0,4142029,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5259941,0,0,0,0,0,0,40,0,0,0,0,0,40,0,0,0,40,40,0,0,0,0,0,40,119,28,0,0,0,0,0,0,8
4666,97109,3/31/2024 0:00:00,2759,0,0,0,0,0,0,14259622,0,0,0,0,0,0,0,23876376,0,0,0,0,0,0,0,0,0,2479425,0,0,0,0,546950,0,0,0,51264857,0,0,0,0,12581909,177,63,2,4,0,0,56,26,15,36,71,63,134,100,0,0,0,106,240,1154,550,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,0,0,0,0,0,15284062,0,0,0,0,0,0,0,20948365,0,0,0,0,0,0,0,0,0,31812,0,0,0,0,188896,0,0,28448,51870711,0,0,0,0,15420940,43,3,10,0,0,0,5,0,6,3,14,3,17,19,0,1,0,29,46,554,748,0,0,0,0,0,0,1501
4668,97111,3/31/2024 0:00:00,21049,0,0,0,0,0,0,7790220,0,0,0,0,0,0,0,6635704,0,0,0,0,0,0,0,0,0,3473540,0,0,0,0,0,0,0,448762,17858801,0,0,0,0,2984115,209,29,0,0,0,0,60,15,103,14,163,29,192,46,0,0,0,46,238,276,313,1,0,0,0,0,0,231
4669,97112,3/31/2024 0:00:00,22698,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17922872,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2503134,0,0,0,22383710,0,0,0,0,1957704,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,286,82,0,0,0,0,0,0,279

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_AS0001,ACCT_AS0003,ACCT_AS0004,ACCT_AS0005,ACCT_AS0010,ACCT_AS0041,ACCT_AS0048,ACCT_AS0050,ACCT_AS0051,ACCT_AS0052,ACCT_AS0053,ACCT_AS0054,ACCT_AS0055,ACCT_AS0056,ACCT_AS0057,ACCT_AS0058,ACCT_AS0059,ACCT_AS0060,ACCT_AS0061,ACCT_AS0062,ACCT_AS0063,ACCT_AS0064,ACCT_AS0065,ACCT_AS0066,ACCT_AS0067,ACCT_AS0068,ACCT_AS0069,ACCT_AS0070,ACCT_AS0071,ACCT_AS0072,ACCT_AS0073,ACCT_DL0121,ACCT_EQ0009,ACCT_IS0004,ACCT_IS0011,ACCT_IS0012,ACCT_IS0013,ACCT_IS0016,ACCT_IS0017,ACCT_IS0021,ACCT_IS0022,ACCT_LC0047,ACCT_LC0085,ACCT_LI0003,ACCT_LI0069,ACCT_LN0050,ACCT_LN0051,ACCT_LN0052,ACCT_LN0053,ACCT_LN0054,ACCT_LN0055,ACCT_LN0056,ACCT_LN0057,ACCT_NW0001,ACCT_NW0002,ACCT_NW0010,ACCT_PC0001,ACCT_PC0002,ACCT_PC0003,ACCT_PC0004,ACCT_PC0005,ACCT_PC0006,ACCT_PC0007,ACCT_PC0008,ACCT_PC0009,ACCT_PC0010,ACCT_SL0003,ACCT_IS0020,ACCT_IS0026,ACCT_IS0046,ACCT_IS0047,ACCT_SL0012,ACCT_SL0013,ACCT_SL0014,ACCT_SL0015,ACCT_SL0016,ACCT_SL0017,ACCT_AS0042
0,1,3/31/2024 0:00:00,2,0,0,39119,0,1,0,30223,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7500,0,0,0,7500,0,0,0,0,0,9859933,0,0,0,0,0,0,0,0,03/01/2023,7500,11187397,0,0,0,0,0,0,0,0,0,0,0,11931,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,0,0,4301286,0,1,0,3132468,0,0,0,0,0,0,0,0,0,0,0,0,5800381,18751062,6467000,2025184,0,33043627,0,0,0,0,0,0,0,-2573281,0,589721,0,0,1380,591101,0,0,0,0,66025,254787898,0,0,0,0,0,0,0,0,01/01/2023,0,275381898,0,0,0,0,0,0,0,0,0,0,0,420808,0,0,0,0,0,136,1973327,0,0,0
2,12,3/31/2024 0:00:00,11,0,883170,175042,55352,1,0,857990,0,0,325000,0,0,325000,0,0,0,0,0,0,0,0,0,0,0,0,1498341,4176868,235491,0,0,5910701,0,0,0,157338,0,0,0,157338,0,0,0,0,0,57007688,0,0,0,0,0,0,0,0,04/01/2023,0,61526262,0,0,0,0,0,0,0,0,0,0,0,279093,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,0,86499882,3004566,2344480,1,0,3301896,0,0,0,0,0,0,0,0,0,0,0,0,0,328381,0,0,0,328381,0,0,0,0,0,0,0,-26347,0,653517,0,0,0,653517,0,0,0,0,0,973006993,0,0,0,0,0,0,0,0,01/01/2023,2278236,1059610146,0,0,0,0,0,0,0,0,0,0,0,1600876,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,0,0,98410,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8382209,0,0,0,0,0,0,0,0,NaN,0,9656630,0,0,0,0,0,0,0,0,0,0,0,7484,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,0,0,341118,22686,1,0,331036,0,0,0,0,0,0,0,0,0,0,0,0,526383,2990448,1668676,3010750,233799,8430055,0,0,0,0,0,0,0,-1060308,0,9000,0,0,0,9000,0,0,0,0,0,61484680,0,0,0,0,0,0,0,0,04/01/2023,310000,67072110,0,0,0,0,0,0,0,0,0,0,0,25617,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,0,129893,4197846,912512,1,0,2733965,0,0,0,0,0,0,0,0,0,0,0,0,4084440,4970840,5730789,26830320,2632747,44249136,0,0,0,0,0,0,0,-7527822,0,391297,0,0,0,391297,0,0,0,0,0,421186519,0,0,0,0,0,0,0,0,01/01/2023,0,465896889,0,0,0,0,0,0,0,0,0,0,0,565947,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,0,8003329,2197947,1929980,1,0,1819404,0,0,0,0,0,0,0,0,0,0,0,0,20007416,7475882,2479628,8941703,607685,39512314,0,0,0,0,0,0,0,-1188490,0,283500,0,0,0,283500,0,0,0,0,0,352943612,0,0,0,0,0,0,0,0,01/01/2023,1075100,384161511,0,0,0,0,0,0,0,0,0,0,0,560894,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,0,0,1387217,0,1,0,832544,47620,0,0,452065,0,499685,0,0,0,0,0,0,982703,1803998,2221302,7015454,906942,12930401,0,0,0,0,0,0,0,-2104649,0,90262,0,0,0,90262,0,0,0,0,0,149360012,2,67985,50989,0,0,0,0,0,01/01/2023,0,158761538,0,0,0,0,0,0,0,0,0,0,0,200142,0,39483,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,0,0,1634602,0,1,0,820600,0,0,0,0,0,0,0,0,0,0,0,0,28835,27689093,16257461,32264595,0,76239984,0,496000,0,0,0,496000,0,-15441535,0,196778,0,0,0,196778,0,0,0,0,0,232132514,0,0,0,0,0,0,0,0,01/01/2023,0,241976246,0,0,0,0,0,0,0,0,0,0,0,131244,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,USER_ID,ACCT_AS0007,ACCT_AS0008,ACCT_AS0009,ACCT_AS0013,ACCT_AS0016,ACCT_AS0017,ACCT_AS0022,ACCT_AS0023,ACCT_AS0024,ACCT_AS0025,ACCT_AS0032,ACCT_AS0036,ACCT_CM0099,ACCT_CH0007,ACCT_CH0008,ACCT_CH0015,ACCT_CH0016,ACCT_CH0017,ACCT_CH0018,ACCT_CH0019,ACCT_CH0020,ACCT_CH0021,ACCT_CH0022,ACCT_CH0023,ACCT_CH0024,ACCT_CH0025,ACCT_CH0026,ACCT_CH0027,ACCT_CH0028,ACCT_CH0029,ACCT_CH0030,ACCT_CH0031,ACCT_CH0032,ACCT_CH0033,ACCT_CH0034,ACCT_CH0035,ACCT_CH0036,ACCT_CH0037,ACCT_CH0038,ACCT_CH0039,ACCT_CH0040,ACCT_CH0047,ACCT_CH0048,ACCT_DL0002,ACCT_DL0009,ACCT_DL0016,...,ACCT_DL0134,ACCT_DL0135,ACCT_DL0136,ACCT_DL0137,ACCT_DL0138,ACCT_DL0139,ACCT_DL0140,ACCT_DL0141,ACCT_DL0142,ACCT_DL0144,ACCT_DL0145,ACCT_DL0146,ACCT_DL0147,ACCT_DT0001,ACCT_DT0002,ACCT_DT0003,ACCT_DT0004,ACCT_DT0005,ACCT_DT0006,ACCT_DT0007,ACCT_DT0008,ACCT_DT0009,ACCT_DT0010,ACCT_DT0011,ACCT_DT0012,ACCT_DT0013,ACCT_DT0014,ACCT_DT0015,ACCT_DT0016,ACCT_IN0001,ACCT_IN0002,ACCT_IN0003,ACCT_IN0004,ACCT_IN0005,ACCT_IN0006,ACCT_IN0007,ACCT_IN0008,ACCT_IS0005,ACCT_IS0010,ACCT_IS0029,ACCT_IS0030,ACCT_LQ0013,ACCT_LQ0014,ACCT_LQ0015,ACCT_LQ0016,ACCT_LQ0017,ACCT_IS0048,ACCT_IS0049,ACCT_DL0148,ACCT_DL0149
0,1,3/31/2024 0:00:00,2,WISe,950000,0,2094411,0,0,2361,0,0,0,0,0,3939,0,6519,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,22606,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,114577,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,WISe,454564,0,34571064,33043627,0,351932,0,0,49400,33100,0,9887193,1127837,185696,59867,0,557,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,81438,0,3533,...,0,0,0,0,0,0,0,689567,136469,0,2505536,78926,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,1739808,0,0,0,0,223,3524313,0,2987798,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,WISe,17215000,0,19380819,6235701,30200,210200,0,0,0,0,0,3396117,0,155574,17745,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7771,2070,0,...,0,0,0,0,0,0,0,93051,0,0,3743,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,708419,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,WISe,100000,0,92201792,328381,4529495,4529495,0,0,256783,0,0,9522201,0,135154,46840,2436,0,0,10525,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5025,0,0,...,0,0,0,0,0,0,0,851140,0,0,1811783,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19262,541853937,0,0,0,0,1,9003,0,5826600,0,0,51797784,0,60082996,0,60082996,492809,204251,9,140310
4,16,3/31/2024 0:00:00,14,WISe,4848202,0,5610352,0,0,40342,0,0,0,0,0,46428,0,7346,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,83560,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,WISe,8765000,0,11552927,8430055,0,140314,0,0,0,0,0,2860225,6474262,39,297,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,15326,8181,0,24702,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40,8569196,0,0,0,316983,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,WISe,5000000,0,40837091,44249136,2461727,4724861,0,0,384766,0,0,12197897,21969870,32259,4326,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,29838,0,0,...,0,0,0,0,0,0,0,269089,0,0,499743,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7769,159904381,0,0,0,0,0,0,0,3501950,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,WISe,18401000,0,42307776,39512314,236300,886923,0,0,184712,0,0,13133857,3476465,0,0,0,0,0,0,0,0,90116,9545,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,32632,0,0,...,0,0,0,0,0,0,0,518445,329025,0,2093150,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2276,35550621,0,0,0,0,486,11699030,0,2958044,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,WISE,3079000,0,17453660,13430086,1476213,2050608,0,0,0,0,0,3888663,15376473,16084,6269,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,832,0,0,...,0,0,0,0,0,0,0,623145,35544,0,219818,0,520500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,697,14240383,0,0,0,0,3,86631,0,1428042,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,WISe,0,0,17789922,76735984,671759,959127,0,0,0,0,0,13252965,0,16713,4008,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,55189,0,0,...,0,0,0,0,0,0,0,310905,0,0,223195,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1433613,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,USER_ID,ACCT_LQ0018,ACCT_LQ0019,ACCT_LQ0020,ACCT_LQ0021,ACCT_LQ0022,ACCT_LQ0023,ACCT_LQ0024,ACCT_LQ0025,ACCT_LQ0026,ACCT_LQ0027,ACCT_LQ0028,ACCT_LQ0029,ACCT_LQ0030,ACCT_LQ0034,ACCT_LQ0035,ACCT_LQ0038,ACCT_LQ0039,ACCT_LQ0040,ACCT_LQ0042,ACCT_LQ0043,ACCT_LQ0044,ACCT_LQ0045,ACCT_LQ0046,ACCT_LQ0047,ACCT_LQ0052,ACCT_LQ0053,ACCT_LQ0056,ACCT_LQ0059,ACCT_LQ0860,ACCT_NV0001,ACCT_NV0002,ACCT_NV0003,ACCT_NV0004,ACCT_NV0013,ACCT_NV0014,ACCT_NV0015,ACCT_NV0016,ACCT_NV0017,ACCT_NV0018,ACCT_NV0019,ACCT_NV0020,ACCT_NV0021,ACCT_NV0022,ACCT_NV0023,ACCT_NV0024,ACCT_NV0025,...,ACCT_NV0158,ACCT_NV0159,ACCT_NV0160,ACCT_NV0161,ACCT_NV0162,ACCT_NV0169,ACCT_NV0170,ACCT_NV0172,ACCT_NV0173,ACCT_SL0036,ACCT_SL0037,ACCT_SL0038,ACCT_SL0039,ACCT_SL0041,ACCT_SL0043,ACCT_SL0045,ACCT_SL0047,ACCT_SL0049,ACCT_SL0051,ACCT_SL0053,ACCT_SL0055,ACCT_SL0056,ACCT_SL0057,ACCT_SL0058,ACCT_SL0059,ACCT_RB0001,ACCT_RB0002,ACCT_RB0003,ACCT_RB0004,ACCT_RB0005,ACCT_RB0006,ACCT_RB0007,ACCT_RB0008,ACCT_RB0009,ACCT_RB0010,ACCT_RB0011,ACCT_RB0012,ACCT_RB0013,ACCT_RB0014,ACCT_RB0015,ACCT_RB0016,ACCT_RB0017,ACCT_RB0018,ACCT_RB0019,ACCT_RB0020,ACCT_RB0021,ACCT_RB0022,ACCT_RB0023,ACCT_RB0024,ACCT_RB0025
0,1,3/31/2024 0:00:00,2,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,952361,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1322439,30223,0,0,30223,0,0,0,108220,1244442,0.0,1244442.0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,6,3/31/2024 0:00:00,7,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7000000,0,0,0,0,0,0,14745834,13484746,0,0,0,0,0,0,14745834,13484746,0,...,33850123,0,0,0,0,0,0,0,0,1739808,0,0,0,153520,0,0,0,0,0,0,0,6686540,2024441,0,0,23167281,3198493,0,0,3198493,0,0,0,2060044,24305730,0.0,24305730.0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5165080,4948353,0,0,497621,471123,0,0,0,0,0,0,497621,471123,0,0,0,...,23660900,0,0,0,0,0,800000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5867901,857990,0,0,857990,0,0,0,551490,6174401,0.0,6174401.0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,WISe,0,0,0,48182950,0,0,0,0,0,0,0,0,0,0,287986175,0,0,166377840,0,166377840,0,293428466,0,0,0,0,0,0,45000000,0,0,0,0,0,0,0,0,0,0,354728,328381,0,0,354728,328381,0,...,4957876,0,0,0,0,0,0,0,0,0,0,929427,0,0,0,0,0,0,0,0,0,0,0,0,0,86176916,3301896,0,0,3301896,0,0,0,7623047,81855765,0.0,81855765.0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,16,3/31/2024 0:00:00,14,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,4888544,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1274421,28574,0,0,28574,0,0,0,84714,1218281,0.0,1218281.0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,993705,936328,0,0,5763115,5202314,0,0,2068149,1764307,0,0,7831264,6966621,0,...,17335370,0,0,0,0,0,0,0,0,4345436,751483,0,0,0,0,0,0,320357,0,0,0,0,0,0,0,6440038,331036,0,0,331036,0,0,0,0,6771074,0.0,6771074.0,0,0,0,0,0,0,0,0,0,0,0,0,0
4666,97109,3/31/2024 0:00:00,2759,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,74118710,0,0,0,0,0,0,0,0,0,0,22008547,0,0,0,0,0,0,0,0,0,0,51533177,44005410,0,0,51533177,44005410,0,...,53973997,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,325000,238035,54716,0,0,0,0,0,52238192,2733965,0,0,2733965,0,0,0,0,54972157,0.0,54972157.0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34627815,0,48467937,0,0,0,8000000,0,0,0,0,0,0,0,3009747,2870820,0,0,8999083,8384113,0,0,28691974,28257381,0,0,37691057,36641494,0,...,58800237,0,0,0,0,0,6227091,0,0,2232812,0,4600,0,0,0,0,0,0,0,0,0,0,0,0,0,31686072,1819404,0,0,1819404,0,0,0,0,33505476,0.0,33505476.0,0,0,0,0,0,0,0,0,0,0,0,0,0
4668,97111,3/31/2024 0:00:00,21049,WISE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9200904,0,11658007,0,0,0,0,0,0,0,0,7000000,0,0,279389,225759,0,0,2988433,2815423,0,0,8650815,7120603,0,0,11639248,9936026,0,...,18559692,0,0,0,0,0,2236338,0,0,3322947,0,0,0,0,0,0,0,0,0,0,0,96557,0,0,0,11506175,832544,0,0,832544,0,0,0,0,12338719,0.0,12338719.0,0,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,76719071,0,0,0,0,0,9857578,8761406,0,0,36744925,30631693,0,0,0,0,0,0,36744925,30631693,0,...,77695111,0,0,0,0,61082,993220,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,27066980,820600,0,0,820600,0,0,0,0,27887580,0.0,27887580.0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,USER_ID,ACCT_RB0026,ACCT_RB0027,ACCT_RB0028,ACCT_RB0029,ACCT_RB0030,ACCT_RB0031,ACCT_RB0032,ACCT_RB0033,ACCT_RB0034,ACCT_RB0035,ACCT_RB0036,ACCT_RB0037,ACCT_RB0038,ACCT_RB0039,ACCT_RB0040,ACCT_RB0041,ACCT_RB0042,ACCT_RB0043,ACCT_RB0044,ACCT_RB0045,ACCT_RB0046,ACCT_RB0047,ACCT_RB0048,ACCT_RB0049,ACCT_RB0050,ACCT_RB0051,ACCT_RB0052,ACCT_RB0053,ACCT_RB0054,ACCT_RB0055,ACCT_RB0056,ACCT_RB0057,ACCT_RB0058,ACCT_RB0059,ACCT_RB0060,ACCT_RB0061,ACCT_RB0062,ACCT_RB0063,ACCT_RB0064,ACCT_RB0065,ACCT_RB0066,ACCT_RB0067,ACCT_RB0068,ACCT_RB0069,ACCT_RB0070,ACCT_RB0071,...,ACCT_RL0030,ACCT_RL0031,ACCT_RL0032,ACCT_RL0033,ACCT_RL0034,ACCT_RL0035,ACCT_RL0036,ACCT_RL0037,ACCT_RL0038,ACCT_RL0039,ACCT_RL0040,ACCT_RL0041,ACCT_RL0042,ACCT_RL0043,ACCT_RL0044,ACCT_RL0045,ACCT_RL0046,ACCT_RL0047,ACCT_RL0048,ACCT_RL0050,ACCT_SH0013,ACCT_SH0018,ACCT_SH0880,ACCT_SL0018,ACCT_SL0019,ACCT_SL0020,ACCT_SL0021,ACCT_SL0022,ACCT_SL0023,ACCT_SL0024,ACCT_SL0026,ACCT_SL0028,ACCT_SL0029,ACCT_SL0030,ACCT_SL0032,ACCT_SL0033,ACCT_SL0034,ACCT_SL0035,ACCT_LR0001,ACCT_LR0002,ACCT_LR0003,ACCT_LR0004,ACCT_LR0005,ACCT_LR0006,ACCT_LR0007,ACCT_LR0008,ACCT_LQ0060,ACCT_LQ0061,ACCT_LQ0062,ACCT_NW0004
0,1,3/31/2024 0:00:00,2,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,2361,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8953804,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9856392,9856392,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5025
1,6,3/31/2024 0:00:00,7,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,33395559,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,159505768,0,0,0,0,0,0,0,1559907,0,0,0,...,9360947,145000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,397,33088721,492275,7121677,208672795,241409795,32737000,298,5264121,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,12,3/31/2024 0:00:00,11,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,6445901,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19438805,0,0,0,0,0,0,0,0,0,0,0,...,3481630,336900,0,0,0,0,0,0,0,0,0,0,0,0,0,0,154,7611810,386900,0,56663796,56663796,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,13,3/31/2024 0:00:00,12,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,4857876,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,624495680,0,0,0,0,0,0,0,1108973,0,0,0,...,63927494,6693664,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3042,307763805,29313453,189377021,842713969,919926247,77212278,3,1108973,0,0,0,0,0,0,0,0,235,0,0,0,0,1,108265946,1023,0,0,0,0,0,220000000,0,0,1526418
4,16,3/31/2024 0:00:00,14,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,40342,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2769332,0,0,0,0,0,0,0,0,0,0,0,...,384167,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,1132141,0,0,8380329,8380329,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,8570369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12713839,0,0,0,0,0,0,0,8569196,0,0,0,...,1339613,95000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,147,22801165,95000,5975710,61377062,61377062,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,207700
4666,97109,3/31/2024 0:00:00,2759,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,48973997,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,211693072,0,0,0,0,0,0,0,34719636,0,0,0,...,14468354,641419,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1704,115379554,3275037,46573432,396173443,396173443,0,0,0,0,0,3,238035,0,0,3,215565,75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4667,97110,3/31/2024 0:00:00,17502,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,40399237,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,135857791,0,0,0,0,0,0,0,6209367,0,0,0,...,38918710,1622909,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1302,131125955,2451209,30598160,348703744,348953744,250000,0,0,0,0,1,160000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7297904,0,720317
4668,97111,3/31/2024 0:00:00,21049,WISE,0,0,0,0,0,0,0,0,0,0,0,0,0,15480694,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,54047008,0,0,0,0,0,0,0,37038332,0,0,0,...,7050166,2085990,0,0,0,0,0,0,1,500000,0,0,0,0,500000,0,590,27432299,3096203,9061064,141912799,141912799,0,3170,4731013,54,4547665,3,499528,3,0,0,0,6,0,0,2,292781,0,0,0,0,0,0,0,0,0,0,0,0
4669,97112,3/31/2024 0:00:00,22698,WISe,0,0,0,0,0,0,0,0,0,0,0,0,0,77695111,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,92946026,0,0,0,0,0,0,0,0,0,0,0,...,3186090,306781,0,0,0,0,0,0,0,0,0,0,0,0,0,0,368,32511186,947781,2598570,231297778,231297778,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_PG0001,ACCT_PG0002,ACCT_PP0037,ACCT_PP0038,ACCT_PP0039,ACCT_PP0040,ACCT_PP0041,ACCT_PP0042,ACCT_PP0043,ACCT_PP0044,ACCT_PP0045,ACCT_PP0046,ACCT_PP0047,ACCT_PP0048,ACCT_PP0049,ACCT_PP0050,ACCT_PP0051,ACCT_PP0052,ACCT_PP0053,ACCT_PP0054,ACCT_PP0055,ACCT_PP0056,ACCT_PP0057,ACCT_PR0001,ACCT_PR0002,ACCT_PR0003,ACCT_PR0004
0,1,3/31/2024 0:00:00,2,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,6,3/31/2024 0:00:00,7,5493006GFSNOUCCL1W91,Combination,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 20 2024 6:00AM
2,12,3/31/2024 0:00:00,11,254900TYE85Q9OTQ5038,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Dec 31 2023 5:00AM
3,13,3/31/2024 0:00:00,12,549300U18MOAH5F95P15,Automated,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 14 2024 6:00AM
4,16,3/31/2024 0:00:00,14,NaN,Manual,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,3/31/2024 0:00:00,14738,NaN,Automated,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1.0,1.0,NaN,NaN
4666,97109,3/31/2024 0:00:00,2759,5493001D5DXR1S70P689,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 3 2024 5:00AM
4667,97110,3/31/2024 0:00:00,17502,NaN,Combination,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4668,97111,3/31/2024 0:00:00,21049,549300N1MCHMZQ2BP498,Combination,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 19 2024 5:00AM
4669,97112,3/31/2024 0:00:00,22698,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,NaN,NaN,NaN

In [220]:
def apply_active_mapping_wide_from_desc_normalized(
    df_wide: pd.DataFrame,
    desc_df: pd.DataFrame,
    *,
    id_cols=('CU_NUMBER', 'CYCLE_DATE', 'JOIN_NUMBER'),
    label_col='AcctName',      
    active_value='ACTIVE',
    keep_code_in_name=True,
    pad: int = 3
) -> pd.DataFrame:
    """
    Wide -> wide: keep only ACTIVE account columns and rename them
    using a normalized key that reconciles 'ACCT_001' vs 'Acct_001' differences.
    """

    # 1) Build normalized mapping from the description table for ACTIVE rows
    desc = desc_df.copy()
    desc['__status_u'] = desc['STATUS'].astype(str).str.upper()
    active_mask = desc['__status_u'] == str(active_value).upper()

    desc['__norm_code'] = desc['Account'].apply(lambda v: normalize_acct_code(v, pad=pad))
    mapping_src = (
        desc.loc[active_mask, ['__norm_code', label_col]]
            .dropna(subset=['__norm_code'])
            .drop_duplicates(subset=['__norm_code'])
    )
    # normalized_code -> label
    acct_map_norm = dict(zip(mapping_src['__norm_code'], mapping_src[label_col]))

    # 2) Identify account-like columns in the wide data and normalize them too
    acct_cols = [c for c in df_wide.columns if c not in id_cols]
    col_norm = {c: normalize_acct_code(c, pad=pad) for c in acct_cols}

    # 3) Keep only columns whose normalized code is ACTIVE in the mapping
    active_cols = [c for c in acct_cols if col_norm.get(c) in acct_map_norm]

    # 4) Build a safe rename map (optionally keep original code in brackets)
    if keep_code_in_name:
        rename_map = {
            c: f"{acct_map_norm[col_norm[c]]} [{c}]"
            for c in active_cols
        }
    else:
        # Guard against duplicate descriptions by appending code when needed
        raw_names = [acct_map_norm[col_norm[c]] for c in active_cols]
        dup = {n for n in raw_names if raw_names.count(n) > 1}
        rename_map = {}
        for c in active_cols:
            new = acct_map_norm[col_norm[c]]
            rename_map[c] = f"{new} [{c}]" if new in dup else new

    # 5) Return wide frame with identifiers + active variables renamed
    out = df_wide[list(id_cols) + active_cols].copy()
    out = out.rename(columns=rename_map)
    return out

In [221]:
df_list = [
    FS220, FS220_a, FS220_b, FS220_c, FS220_d, FS220_g, FS220_h,
    FS220_i, FS220_j, FS220_k, FS220_l, FS220_m, FS220_n,
    FS220_p, FS220_q, FS220_r, FS220_s
]

In [222]:
datasets = {
    "fs220": FS220,
    "fs220a": FS220_a,
    "fs220b": FS220_b,
    "fs220c": FS220_c,
    "fs220d":FS220_d,
    "fs220g":FS220_g,
    "fs220i":FS220_i,
    "fs220j": FS220_j,
    "fs220k":FS220_k,
    "fs220l":FS220_l,
    "fs220m":FS220_m,
    "fs220n":FS220_n,
    "fs220p":FS220_p,
    "fs220q":FS220_q,
    "fs220r":FS220_r,
    "fs220s":FS220_s
}

cleaned = {
    name: apply_active_mapping_wide_from_desc_normalized(
        df_wide=df,
        desc_df=acct_description,
        id_cols=('CU_NUMBER','CYCLE_DATE','JOIN_NUMBER'),
        label_col='AcctName',
        active_value='ACTIVE',
        keep_code_in_name=True,
        pad=3
    )
    for name, df in datasets.items()
}

In [223]:
def prep_index(df):
    return (df
            .assign(CYCLE_DATE=pd.to_datetime(df['CYCLE_DATE']).dt.date)
            .set_index(['CU_NUMBER','CYCLE_DATE','JOIN_NUMBER'])
            .sort_index())

frames_idx = [prep_index(df) for df in cleaned.values()]
combined_wide = reduce(lambda L, R: L.join(R, how='outer', rsuffix='_dup'), frames_idx).reset_index()

In [224]:
combined_wide

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,Land and Building [ACCT_007],Other Fixed Assets [ACCT_008],"Other Assets, Accrued Interest on Loans [ACCT_009]",TOTAL ASSETS [ACCT_010],Total Amount of Shares [ACCT_013],Total Amount of Shares and Deposits [ACCT_018],Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 2 to less than 6 months delinquent [ACCT_021B],Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 6 to less than 12 months delinquent [ACCT_022B],Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 12 months and over delinquent [ACCT_023B],Total number of Loans and Leases [ACCT_025A],Total number of Loans and Leases [ACCT_025B],Loans Granted Year-to-Date [ACCT_031A],Loans Granted Year-to-Date [ACCT_031B],Number of Total Delinquent Loans & Leases (Two or more months) [ACCT_041B],Outstanding Balance of Member Commercial Loans Secured by Farmland [ACCT_042],"Borrowing Repurchase Transactions, Amount < 1 Year [ACCT_058C]",Total Uninsured Member Shares and Deposits > $250K (A+A1+B+C+D+E) [ACCT_065],Total Uninsured Nonmember Shares and Deposits > $250K (G+H+I) [ACCT_067],Total Uninsured Shares and Deposits > $250K (F+J) [ACCT_068],Total Insured Shares and Deposits > $250K (item 17 less item K) [ACCT_069],Number of current members (not number of accounts) [ACCT_083],Number of potential members [ACCT_084],Provision for Loan & Lease Losses [ACCT_300],Interest on Borrowed Money [ACCT_340],Dividends on Shares (Includes dividends earned during current period) [ACCT_380],Amount of Total Loans/Lines of Credit Secured by Junior Lien 1-4 Family Residential Properties [ACCT_386],Net Member Business Loan Balance [ACCT_400],Non-Member Deposits [ACCT_457],Interest Rate of Unsecured Credit Card Loans [ACCT_521],Interest Rate of All Other Unsecured Loans/Lines of Credit [ACCT_522],Interest Rate of New Vehicle Loans [ACCT_523],Interest Rate of Used Vehicle Loans [ACCT_524],Total Amount of All Loans Charged Off Year-to-Date [ACCT_550],Total Amount of All Year-to-Date Recoveries on Charged-Off Loans [ACCT_551],Interest Rate of Total Loans/Lines of Credit Secured by Junior Lien 1-4 Family Residential Properties [ACCT_562],Interest Rate of Total Loans/Lines of Credit Secured by 1st Lien 1-4 Family Residential Properties [ACCT_563],Net Income (unless the amount is already included in Undivided Earnings) [ACCT_602],Total Amount of All Other Shares [ACCT_630],Amount of Leases Receivable [ACCT_002__DUP2],Amount of Leases Receivable [ACCT_002__DUP4],Amount of Regular Shares [ACCT_657],Other Reserves (Appropriations for Undivided Earnings) [ACCT_658],Appropriation for Non-Conforming Investments (SCU ONLY) [ACCT_668],Total Non-Interest Expense (Sum of items 18-27) [ACCT_671],Amount of Leases Receivable [ACCT_002__DUP6],Amount of Total Loans/Lines of Credit Secured by 1st Lien 1-4 Family Residential Properties [ACCT_703],Balance Outstanding of 1st Mtg Residential construction Loans - Excluding Commercial Purpose [ACCT_704],...,Commercial Foreclosed and Repossessed Assets [ACCT_0022__DUP74],Consumer Real Estate Foreclosed and Repossessed Assets [ACCT_0023__DUP75],Consumer Vehicle Foreclosed and Repossessed Assets [ACCT_0024__DUP76],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit Secured by Farmland [ACCT_0026__DUP77],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit Secured by Multifamily [ACCT_0028__DUP78],"Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit Secured by Owner Occupied, Non-Farm, Non-Residential Property [ACCT_0029__DUP79]","Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit Secured by Owner Occupied, Non-Farm, Non-Residential Property [ACCT_0030__DUP80]",Other intangible assets [ACCT_0032__DUP81],Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Loans to finance agricultural production and other loans to farmers [ACCT_0033__DUP82],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit - Loans to finance agricultural production and other loans to farmers [ACCT_0034__DUP83],Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Commercial and Industrial Loans [ACCT_0035__DUP84],Interest Rate Derivative Purchased Options Total Notional Amount [ACCT_0001__DUP85],Unsecured Credit Card Loans [ACCT_0002__DUP86],Cash on Deposit in the Federal Reserve Bank [ACCT_0003__DUP87],Coin and Currency [ACCT_0004__DUP88],Cash Items in Process of Collection [ACCT_0005__DUP89],Interest Rate Derivative Swaps Net Fair Value Gain (Loss) [ACCT_0006__DUP90],"Time deposits in commercial banks, S&Ls, savings banks, natural person credit unions, or corporate credit unions [ACCT_0007__DUP91]",All other deposits [ACCT_0008__DUP92],Trading Debt Securities > 10 Years [ACCT_0060__DUP93],Total Trading Debt Securities [ACCT_0061__DUP94],Available-for-sale Debt Securities <=1 Year [ACCT_0062__DUP95],Coin and Currency [ACCT_0004__DUP96],Interest Rate Derivative Purchased Options Total Notional Amount [ACCT_0001__DUP1]_dup,Unsecured Credit Card Loans [ACCT_0002__DUP2],Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Unsecured Commercial Loans [ACCT_0037],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit - Unsecured Commercial Loans [ACCT_0038]_dup,Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Unsecured Revolving Lines of Credit for Commercial Purposes [ACCT_0039]_dup,Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit - Unsecured Revolving Lines of Credit for Commercial Purposes [ACCT_0040]_dup,(CECL) Allowance for Credit Losses on Held-To-Maturity Debt Securities [ACCT_0041]_dup,CECL (Allowance for Credit Losses on Available-for-Sale Debt Securities) [ACCT_0042]_dup,Borrowing Arrangements - Assets Pledged to Secure All Outstanding Borrowings - Federal Home Loan Bank [ACCT_0043],Leases Receivable [ACCT_0044]_dup,Borrowing Arrangements - Assets Pledged to Secure All Outstanding Borrowings - Central Liquidity Facility [ACCT_0045],Gain (Loss) on Equity and Trading Debt Securities [ACCT_0046]_dup,Whole or Partial Loans Purchased Under 701.23 - YTD Charge Offs [ACCT_0047]_dup,(CECL) Allowance for Credit Losses on Loans and Leases [ACCT_0048]_dup,Non-Sufficient Funds Fee Income [ACCT_0049]_dup,Equity Securities <=1 Year [ACCT_0050]_dup,Equity Securities >1 and <=3 Years [ACCT_0051]_dup,Equity Securities >3 and <=5 Years [ACCT_0052]_dup,Equity Securities >5 and <= 10 Years [ACCT_0053]_dup,Equity Securities > 10 Years [ACCT_0054]_dup,Total Equity Securities [ACCT_0055]_dup,Trading Debt Securities <=1 Year [ACCT_0056]_dup,Trading Debt Securities >1 and <=3 Years [ACCT_0057]_dup,Interest Rate Derivative Purchased Options Total Notional Amount [ACCT_0001__DUP3],Unsecured Credit Card Loans [ACCT_0002__DUP4],Cash on Deposit in the Federal Reserve Bank [ACCT_0003],Coin and Currency [ACCT_0004]
0,1,2024-03-31,2,42402,7458,0,11182372,9856392,9856392,46439,478,0,767,8953804,31,720671,69523,0,0,0,0,0,0,1276,2000,0,0,32327,0,0,0,0.0,925.0,674.0,674.0,6519,696,0,0,29922,88074,0,0,6715796,203071,0,95898,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5025,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,6,2024-03-31,7,2926739,1436871,0,275381898,208672795,241409795,1111383,826955,93026,20300,194154396,1090,14248221,2720931,0,0,0,0,0,0,28945,70000,0,112,788080,0,0,32737,1074.0,1184.0,500.0,666.0,367890,115903,0,0,0,275698,0,0,121112510,0,0,3628514,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493006GFSNOUCCL1W91,Combination,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 20 2024 6:00AM
2,12,2024-03-31,11,5004004,555306,0,61526262,56663797,56663797,152053,2677,0,8001,27050615,609,2777539,247781,0,0,0,0,0,0,9133,19133,0,15588,85617,0,0,0,1243.0,1050.0,800.0,875.0,206482,30395,0,0,0,379808,0,0,26235674,0,0,1201434,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,254900TYE85Q9OTQ5038,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Dec 31 2023 5:00AM
3,13,2024-03-31,12,12889552,665915,0,1058083728,842713968,919926247,849774,962009,0,35885,933368458,7449,99199184,2662923,0,0,0,0,0,0,65941,849530,0,542312,6944265,0,0,22,950.0,950.0,364.0,364.0,769471,201614,0,0,0,234783,0,0,172985942,0,0,6030987,0,0,0,...,0,0,0,0,0,0,235,0,0,0,0,1,108265946,1023,0,0,0,0,0,220000000,0,0,1526418,549300U18MOAH5F95P15,Automated,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 14 2024 6:00AM
4,16,2024-03-31,14,0,1893,0,9656630,8380331,8380331,0,529,16340,280,3901475,14,239962,16869,0,0,0,0,0,0,900,1320,0,45,10053,0,0,0,1490.0,850.0,624.0,699.0,21311,183,0,0,0,0,0,0,4977160,479074,0,92646,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Manual,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4665,97108,2024-03-31,14738,0,127724,0,66864410,61377062,61377062,27701,0,0,88294,44084201,44,2331916,43027,0,0,0,0,0,0,2655,3895000,0,116,361505,0,0,0,1294.0,1200.0,725.0,850.0,33080,8854,0,0,-56864,0,0,0,18904383,0,0,402335,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,207700,NaN,Automated,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,1.0,1.0,NaN,NaN
4666,97109,2024-03-31,2759,4170475,274366,0,465896889,396173443,396173443,278727,226016,0,18482,361792262,832,22302047,773832,0,0,0,0,0,0,25883,500000,0,189139,1936840,0,0,0,1450.0,1349.0,750.0,860.0,361335,117940,0,0,896288,447680,0,0,113933357,0,0,3425118,0,0,0,...,3,238035,0,0,3,215565,75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493001D5DXR1S70P689,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 3 2024 5:00AM
4667,97110,2024-03-31,17502,15013790,795315,0,383441194,348703744,348953744,562189,933008,155891,13814,273193111,553,10987820,2169533,0,0,0,0,0,0,24762,255994,0,0,1520398,0,0,1,1699.0,1324.0,849.0,924.0,356658,47568,0,0,277626,7954429,0,0,66089346,0,0,3479604,0,0,0,...,1,160000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7297904,0,720317,NaN,Combination,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4668,97111,2024-03-31,21049,4067996,685430,0,158761538,141912799,141912799,99699,38370,0,8065,118017639,543,9623913,761214,0,0,0,0,0,0,12808,900000,0,48533,570310,0,0,0,1263.0,960.0,533.0,689.0,143368,36308,0,0,0,215962,0,0,53203424,0,0,1388587,0,0,0,...,3,499528,3,0,0,0,6,0,0,2,292781,0,0,0,0,0,0,0,0,0,0,0,0,549300N1MCHMZQ2BP498,Combination,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 19 2024 5:00AM
4669,97112,2024-03-31,22698,8117822,483814,0,241976246,231297778,231297778,199692,38054,0,11363,125457212,329,5299557,548651,0,0,0,0,0,0,21360,3600578,0,0,712200,0,0,0,833.0,880.0,481.0,492.0,292172,18177,0,0,0,0,0,0,100572837,0,0,2120760,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,NaN,NaN,NaN

In [225]:
assets = [c for c in combined_wide.columns if "asset" in c.lower()]
combined_wide[assets].shape
combined_wide.head()

(4670, 129)

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,Land and Building [ACCT_007],Other Fixed Assets [ACCT_008],"Other Assets, Accrued Interest on Loans [ACCT_009]",TOTAL ASSETS [ACCT_010],Total Amount of Shares [ACCT_013],Total Amount of Shares and Deposits [ACCT_018],Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 2 to less than 6 months delinquent [ACCT_021B],Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 6 to less than 12 months delinquent [ACCT_022B],Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 12 months and over delinquent [ACCT_023B],Total number of Loans and Leases [ACCT_025A],Total number of Loans and Leases [ACCT_025B],Loans Granted Year-to-Date [ACCT_031A],Loans Granted Year-to-Date [ACCT_031B],Number of Total Delinquent Loans & Leases (Two or more months) [ACCT_041B],Outstanding Balance of Member Commercial Loans Secured by Farmland [ACCT_042],"Borrowing Repurchase Transactions, Amount < 1 Year [ACCT_058C]",Total Uninsured Member Shares and Deposits > $250K (A+A1+B+C+D+E) [ACCT_065],Total Uninsured Nonmember Shares and Deposits > $250K (G+H+I) [ACCT_067],Total Uninsured Shares and Deposits > $250K (F+J) [ACCT_068],Total Insured Shares and Deposits > $250K (item 17 less item K) [ACCT_069],Number of current members (not number of accounts) [ACCT_083],Number of potential members [ACCT_084],Provision for Loan & Lease Losses [ACCT_300],Interest on Borrowed Money [ACCT_340],Dividends on Shares (Includes dividends earned during current period) [ACCT_380],Amount of Total Loans/Lines of Credit Secured by Junior Lien 1-4 Family Residential Properties [ACCT_386],Net Member Business Loan Balance [ACCT_400],Non-Member Deposits [ACCT_457],Interest Rate of Unsecured Credit Card Loans [ACCT_521],Interest Rate of All Other Unsecured Loans/Lines of Credit [ACCT_522],Interest Rate of New Vehicle Loans [ACCT_523],Interest Rate of Used Vehicle Loans [ACCT_524],Total Amount of All Loans Charged Off Year-to-Date [ACCT_550],Total Amount of All Year-to-Date Recoveries on Charged-Off Loans [ACCT_551],Interest Rate of Total Loans/Lines of Credit Secured by Junior Lien 1-4 Family Residential Properties [ACCT_562],Interest Rate of Total Loans/Lines of Credit Secured by 1st Lien 1-4 Family Residential Properties [ACCT_563],Net Income (unless the amount is already included in Undivided Earnings) [ACCT_602],Total Amount of All Other Shares [ACCT_630],Amount of Leases Receivable [ACCT_002__DUP2],Amount of Leases Receivable [ACCT_002__DUP4],Amount of Regular Shares [ACCT_657],Other Reserves (Appropriations for Undivided Earnings) [ACCT_658],Appropriation for Non-Conforming Investments (SCU ONLY) [ACCT_668],Total Non-Interest Expense (Sum of items 18-27) [ACCT_671],Amount of Leases Receivable [ACCT_002__DUP6],Amount of Total Loans/Lines of Credit Secured by 1st Lien 1-4 Family Residential Properties [ACCT_703],Balance Outstanding of 1st Mtg Residential construction Loans - Excluding Commercial Purpose [ACCT_704],...,Commercial Foreclosed and Repossessed Assets [ACCT_0022__DUP74],Consumer Real Estate Foreclosed and Repossessed Assets [ACCT_0023__DUP75],Consumer Vehicle Foreclosed and Repossessed Assets [ACCT_0024__DUP76],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit Secured by Farmland [ACCT_0026__DUP77],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit Secured by Multifamily [ACCT_0028__DUP78],"Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit Secured by Owner Occupied, Non-Farm, Non-Residential Property [ACCT_0029__DUP79]","Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit Secured by Owner Occupied, Non-Farm, Non-Residential Property [ACCT_0030__DUP80]",Other intangible assets [ACCT_0032__DUP81],Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Loans to finance agricultural production and other loans to farmers [ACCT_0033__DUP82],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit - Loans to finance agricultural production and other loans to farmers [ACCT_0034__DUP83],Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Commercial and Industrial Loans [ACCT_0035__DUP84],Interest Rate Derivative Purchased Options Total Notional Amount [ACCT_0001__DUP85],Unsecured Credit Card Loans [ACCT_0002__DUP86],Cash on Deposit in the Federal Reserve Bank [ACCT_0003__DUP87],Coin and Currency [ACCT_0004__DUP88],Cash Items in Process of Collection [ACCT_0005__DUP89],Interest Rate Derivative Swaps Net Fair Value Gain (Loss) [ACCT_0006__DUP90],"Time deposits in commercial banks, S&Ls, savings banks, natural person credit unions, or corporate credit unions [ACCT_0007__DUP91]",All other deposits [ACCT_0008__DUP92],Trading Debt Securities > 10 Years [ACCT_0060__DUP93],Total Trading Debt Securities [ACCT_0061__DUP94],Available-for-sale Debt Securities <=1 Year [ACCT_0062__DUP95],Coin and Currency [ACCT_0004__DUP96],Interest Rate Derivative Purchased Options Total Notional Amount [ACCT_0001__DUP1]_dup,Unsecured Credit Card Loans [ACCT_0002__DUP2],Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Unsecured Commercial Loans [ACCT_0037],Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit - Unsecured Commercial Loans [ACCT_0038]_dup,Loan Loss Information - YTD Charge Offs - Commercial Loans/Lines of Credit - Unsecured Revolving Lines of Credit for Commercial Purposes [ACCT_0039]_dup,Loan Loss Information - YTD Recoveries - Commercial Loans/Lines of Credit - Unsecured Revolving Lines of Credit for Commercial Purposes [ACCT_0040]_dup,(CECL) Allowance for Credit Losses on Held-To-Maturity Debt Securities [ACCT_0041]_dup,CECL (Allowance for Credit Losses on Available-for-Sale Debt Securities) [ACCT_0042]_dup,Borrowing Arrangements - Assets Pledged to Secure All Outstanding Borrowings - Federal Home Loan Bank [ACCT_0043],Leases Receivable [ACCT_0044]_dup,Borrowing Arrangements - Assets Pledged to Secure All Outstanding Borrowings - Central Liquidity Facility [ACCT_0045],Gain (Loss) on Equity and Trading Debt Securities [ACCT_0046]_dup,Whole or Partial Loans Purchased Under 701.23 - YTD Charge Offs [ACCT_0047]_dup,(CECL) Allowance for Credit Losses on Loans and Leases [ACCT_0048]_dup,Non-Sufficient Funds Fee Income [ACCT_0049]_dup,Equity Securities <=1 Year [ACCT_0050]_dup,Equity Securities >1 and <=3 Years [ACCT_0051]_dup,Equity Securities >3 and <=5 Years [ACCT_0052]_dup,Equity Securities >5 and <= 10 Years [ACCT_0053]_dup,Equity Securities > 10 Years [ACCT_0054]_dup,Total Equity Securities [ACCT_0055]_dup,Trading Debt Securities <=1 Year [ACCT_0056]_dup,Trading Debt Securities >1 and <=3 Years [ACCT_0057]_dup,Interest Rate Derivative Purchased Options Total Notional Amount [ACCT_0001__DUP3],Unsecured Credit Card Loans [ACCT_0002__DUP4],Cash on Deposit in the Federal Reserve Bank [ACCT_0003],Coin and Currency [ACCT_0004]
0,1,2024-03-31,2,42402,7458,0,11182372,9856392,9856392,46439,478,0,767,8953804,31,720671,69523,0,0,0,0,0,0,1276,2000,0,0,32327,0,0,0,0.0,925.0,674.0,674.0,6519,696,0,0,29922,88074,0,0,6715796,203071,0,95898,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5025,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,6,2024-03-31,7,2926739,1436871,0,275381898,208672795,241409795,1111383,826955,93026,20300,194154396,1090,14248221,2720931,0,0,0,0,0,0,28945,70000,0,112,788080,0,0,32737,1074.0,1184.0,500.0,666.0,367890,115903,0,0,0,275698,0,0,121112510,0,0,3628514,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493006GFSNOUCCL1W91,Combination,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 20 2024 6:00AM
2,12,2024-03-31,11,5004004,555306,0,61526262,56663797,56663797,152053,2677,0,8001,27050615,609,2777539,247781,0,0,0,0,0,0,9133,19133,0,15588,85617,0,0,0,1243.0,1050.0,800.0,875.0,206482,30395,0,0,0,379808,0,0,26235674,0,0,1201434,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,254900TYE85Q9OTQ5038,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Dec 31 2023 5:00AM
3,13,2024-03-31,12,12889552,665915,0,1058083728,842713968,919926247,849774,962009,0,35885,933368458,7449,99199184,2662923,0,0,0,0,0,0,65941,849530,0,542312,6944265,0,0,22,950.0,950.0,364.0,364.0,769471,201614,0,0,0,234783,0,0,172985942,0,0,6030987,0,0,0,...,0,0,0,0,0,0,235,0,0,0,0,1,108265946,1023,0,0,0,0,0,220000000,0,0,1526418,549300U18MOAH5F95P15,Automated,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 14 2024 6:00AM
4,16,2024-03-31,14,0,1893,0,9656630,8380331,8380331,0,529,16340,280,3901475,14,239962,16869,0,0,0,0,0,0,900,1320,0,45,10053,0,0,0,1490.0,850.0,624.0,699.0,21311,183,0,0,0,0,0,0,4977160,479074,0,92646,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Manual,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN