# Project Roadmap: Characteristics of Successful Credit Unions

## 1. Introduction & Motivation

### 1.1 Why study credit unions?

Credit unions are member-owned, community-focused financial institutions.

Just as banks do, credit unions accept deposits, make loans, and provide a wide array of other financial services. But as member-owned institutions, credit unions focus on providing personalized service, a safe place to save and borrow at reasonable rates. They also provide financial education and support through workshops or one on one sessions. Unlike banks, credit unions return surplus income to their members in the form of lower interest loans, higher saving rates or reduced/eliminated fees.

### 1.2 Research question:

What distinguishes successful credit unions from less successful ones?

## 2. Data & Preparation

### 2.1 Source: 
NCUA Call Report (FS220) data.

### 2.2 Time Frame: 
For the purposes of this analysis, we will work on data from 2024. Later, we plan to expand to multiple quarters/years.

### 2.3 Cleaning:

- Normalize ID columns (CU_NUMBER, CYCLE_DATE, JOIN_NUMBER).

- Keep only active accounts (drop inactive).

- Map account codes to descriptive names.

- Explore numeric vs. categorical variables: df.nunique().sort_values()

- Select data by availability: drop columns that are 40%+ missing (or some other threshold)

- Group variables into broad themes: Capital/Net Worth, Assets, Loans, Shares & Deposits, Delinquencies, Income & Expenses, Membership

- Build a list of KPIs: Worth Ratio , Net Interest Margin, Return on Assets (ROA), Loan-to-Share Ratio, Risk-Adjusted Return on Capital, Efficiency Ratio, Loan-to-Deposit Ratio, Yield-on-Loans, Cost of Total Deposits, Delinquency Ratio (30+ days), Liquidity Ratio, Membership Growth

A good source (https://www.stratadecision.com/blog/10-key-financial-metrics-kpis-banks-credit-unionsNet



## 3. Exploratory Data Analysis

### 3.1 Visual Exploration

Histograms/boxplots: What’s the distribution of net worth ratio, delinquency, etc.?

Heatmaps: Correlation between capital, loans, and delinquencies.

Time plots (once we add multiple quarters): Which KPIs are trending?

### 3.2 Defining Success

Decide how to measure it. Options:

- Net Worth Ratio (primary capital adequacy metric).

- Return on Assets (ROA) (profitability).

- Membership Growth (engagement).

For example, we can have the following cutoff threshold. 

Successful CU = Top 25% by Net Worth Ratio.

Struggling CU = Bottom 25%.

### 3.3 Compare successful vs. struggling CUs across major themes:

- Size: Total assets, membership. </br>

- Balance sheet mix: Loan-to-Share ratio, investment balances. </br>

- Asset quality: Delinquency ratios, charge-offs.</br>

- Liquidity & funding: Share/deposit structure, borrowings.</br>

- Income/expenses: Net income, fee income, operating costs.</br>

Deliverable: Side-by-side distributions, bar plots, boxplots.</br>


## 4. Statistical & Predictive Analysis

Correlations: Which variables correlate most with success?

Logistic regression / tree models: Predict success (binary target = top quartile or not).

Feature importance: Which factors matter most (e.g., asset size, delinquency)?

Deliverable: Table of top predictors + a simple predictive model.


## 5.  Benchmarks & Peer Groups


We can break the analysis down further:

By asset size: small (< 100Million), medium, large (>1B).

By region: West, South, Midwest, etc.

That way we get to see if success drivers differ across groups.

## 6. Visualization / Dashboard

Interactive dashboard (e.g., Plotly, Dash, or Streamlit).

Key metrics: Net Worth, Loans, Delinquency, ROA, Membership Growth.

Filters: by size, region.

Deliverable: “Credit Union Health Explorer” dashboard.

## 7. Conclusion & Insights

### 7.1 Summary:

What are the factors that consistently show up among successful credit unions? Are they structural (e.g., size, location) or management-driven (loan mix, expenses)?

### 7.2 Implications for:

Credit union leaders, Policymakers, Researchers

In [1]:
import os
import re
from pathlib import Path
from functools import reduce
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor

# Display settings
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
pd.set_option('display.max_columns', 100)
sns.set(style='whitegrid')

# Logging
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.info("Notebook started.")

INFO:__main__:Notebook started.

# 1. Paths

In [2]:
# Define paths
DATA_DIR = "../data/raw"
PROCESSED_DIR = "../data/processed"

# 2. Description File

In [3]:
file_path_desc = os.path.join(DATA_DIR, "call-report-data-2024-03/AcctDesc.txt") 

try:
    acct_description = pd.read_csv(file_path_desc)
    logger.info(f"Loaded dataset with shape {acct_description.shape}")
except Exception as e:
    logger.error(f"Failed to load file: {e}")

INFO:__main__:Loaded dataset with shape (3377, 12)

In [4]:
acct_description.head()
acct_description.columns

,Account,AcctName,AcctDesc,TableName,Annualize,CBSAccount,FPRAccount,STATAcctMain,STATAcctState,STATAcctGraph,STATAcctTable8,STATUS
0,Acct_001,Amount - Total Other Loans (Purchased or to no...,Include the dollar amount of outstanding loans...,FS220A,False,True,True,True,True,False,False,Inactive
1,Acct_002,Amount of Leases Receivable,"Leases Receivable. Include the rate, number, a...",FS220A,False,False,False,False,False,False,False,Active
2,Acct_003,Loans Held for Sale,Loans Held for Sale. Report the amount of outs...,FS220C,False,False,False,False,False,False,False,Active
3,Acct_007,Land and Building,"Land and building, less depreciation on buildi...",FS220,False,True,True,True,True,False,True,Active
4,Acct_008,Other Fixed Assets,All other fixed assets such as furniture and f...,FS220,False,True,True,True,True,False,True,Active

Index(['Account', 'AcctName', 'AcctDesc', 'TableName', 'Annualize',
       'CBSAccount', 'FPRAccount', 'STATAcctMain', 'STATAcctState',
       'STATAcctGraph', 'STATAcctTable8', 'STATUS'],
      dtype='object')

# 3. Drop Inactive Accounts And Select Accounts In Financial Performance Report (FPR)

In [5]:
account_desc_active = acct_description[
    (acct_description['STATUS'] == 'Active') &
    (acct_description['FPRAccount'])
]

In [6]:
account_desc_active

,Account,AcctName,AcctDesc,TableName,Annualize,CBSAccount,FPRAccount,STATAcctMain,STATAcctState,STATAcctGraph,STATAcctTable8,STATUS
3,Acct_007,Land and Building,"Land and building, less depreciation on buildi...",FS220,False,True,True,True,True,False,True,Active
4,Acct_008,Other Fixed Assets,All other fixed assets such as furniture and f...,FS220,False,True,True,True,True,False,True,Active
13,Acct_010,TOTAL ASSETS,TOTAL ASSETS,FS220,False,True,True,True,True,True,True,Active
21,Acct_013,Total Amount of Shares,The sum of all shares excluding non-member dep...,FS220,False,False,True,True,False,False,False,Active
25,Acct_014,"TOTAL LIABILITIES, SHARES, AND EQUITY","TOTAL LIABILITIES, SHARES, AND EQUITY",FS220A,False,True,True,True,True,False,False,Active
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,Acct_908C,Total Amount of Share Certificates,Report the total dollar amount for credit unio...,FS220,False,True,True,True,True,False,False,Active
2495,Acct_911,Total Amount of Money Market Shares,Report the dollar amount of credit union money...,FS220,False,True,True,True,True,False,False,Active
2504,Acct_925A,Total Subordinated Debt included in Net Worth,Total Subordinated Debt included in Net Worth,FS220A,False,True,True,True,True,True,True,Active
2513,Acct_940,Undivided Earnings,Represents the accumulated surplus net income ...,FS220,False,True,True,True,True,True,True,Active
2534,Acct_961A5,Number of member commercial loans Secured by F...,Number of member commercial loans Secured by F...,FS220M,False,True,True,False,False,False,False,Active

# 4. What Do The Column Names Mean?

**What is a Call Report System?** 

In the context of credit unions, the Call Report System refers to a standardized reporting framework where credit unions submit detailed financial and operational data to regulators. It’s similar to the quarterly reports that banks submit to the FDIC.

**What It Contains**

The Call Report collects comprehensive data about a credit union’s:

1. Balance sheet (assets, liabilities, capital)

2. Income statement (interest income, non-interest income, expenses)

3. Lending activity (types of loans, delinquency, charge-offs)

4. Shares and deposits

5. Investment portfolio

6. Operational metrics (membership size, net worth ratio, loan-to-share ratio, delinquency ratios, etc.)




**CBSAccount**	Indicates whether the account is used in the Call Report system (CBS) — the core regulatory report that credit unions submit to the NCUA. Usually True/False.

**FPRAccount**	Flags whether this account is included in the Financial Performance Report (FPR), which summarizes key performance indicators.

**STATAcctMain**	True if the account is used in the main statistical report by the NCUA or analysts. Typically part of core metrics used for national trends.

**STATAcctState**	True if the account is used for state-level summaries or reports.

**STATAcctGraph**	True if the account is used in visualizations/graphs in published reports (like NCUA's quarterly charts).

**STATAcctTable8**	True if the account appears in Table 8 of NCUA’s standard reporting tables (one of the summary tables presented each quarter).

# 5. Defining and Understanding Key Performance Indicators (KPIs)

1. **Financial Health KPIs**

These measure profitability, stability, and overall balance sheet performance:

Net Worth Ratio (Capital Adequacy) → Net worth ÷ Total assets. Regulators (like NCUA in the U.S.) expect ≥7% to be considered “well-capitalized.”

Return on Assets (ROA) → Net income ÷ Average total assets. Shows profitability relative to asset size.

Loan-to-Share Ratio (LTS) → Loans outstanding ÷ Member shares. Measures lending aggressiveness vs. liquidity.

Delinquency Ratio → Delinquent loans ÷ Total loans. Indicates credit risk.

Charge-Off Ratio → Net charge-offs ÷ Average loans. Tracks loan losses.

Operating Expense Ratio → Operating expenses ÷ Average assets. Lower is better for efficiency.

2. **Liquidity & Risk KPIs**
Net Interest Margin (NIM) → (Interest income − Interest expense) ÷ Average earning assets.

Liquidity Ratio → Liquid assets ÷ Total assets. Ensures the CU can meet withdrawals.

Allowance for Loan Losses (ALLL) Coverage Ratio → ALLL ÷ Delinquent loans.

3. **Membership & Growth KPIs**
Credit unions are member-focused, so growth and engagement matter:

Membership Growth Rate → (New members − Exiting members) ÷ Total members.

Average Member Relationship (AMR) → Total loans + Shares ÷ Members. Measures product penetration.

Product Penetration Rate → e.g., % of members with checking, loans, or credit cards.

Share Growth Rate → Member deposits growth.

Loan Growth Rate → Year-over-year loan growth.

4. **Member Satisfaction KPIs**
Net Promoter Score (NPS) → Measures member loyalty and likelihood to recommend.

Member Retention Rate → % of members who stay year-over-year.

Digital Engagement Metrics → Online banking/mobile usage rates.

5. **Regulatory/Compliance KPIs**
CAMEL Ratings (Capital, Asset quality, Management, Earnings, Liquidity) – used by regulators.

Concentration Ratios → Limits on certain loan categories (e.g., real estate).

# 6 a. Create a Mapping of Accounts and Their Names From The Description Files

In [551]:
acct_map = account_desc_active.set_index('Account')['AcctName'].dropna().to_dict()

{'Acct_001': 'Amount - Total Other Loans (Purchased or to non-members)', </br>
 'Acct_002': 'Amount of Leases Receivable',</br>
 'Acct_003': 'Loans Held for Sale',</br>
 'Acct_007': 'Land and Building',</br>
 'Acct_008': 'Other Fixed Assets',</br>
 'Acct_009': 'Other Assets',</br>
 'Acct_009A': 'Other Assets, Accrued Interest on Loans',</br>
 'Acct_009B': 'Other Assets, Accrued Interest on Investments',</br>
 'Acct_009C': 'Other Assets, All Other',</br>
 'Acct_009D': 'Total Intangible Assets,'</br>
 'Acct_009D1': 'Identifiable Intangible Assets',</br>
 'Acct_009D2': 'Goodwill',</br>
 'Acct_009E': 'Non-Trading Derivative Assets',</br>
 'Acct_010': 'TOTAL ASSETS'}...etc</br>

# 6 b. Create a Mapping of Accounts and Their Descriptions From The Description Files

In [552]:
acct_detailed_desc = account_desc_active.set_index('Account')['AcctDesc'].dropna().to_dict()

{'Acct_001': 'Include the dollar amount of outstanding loans involving repossession of collateral, any note or contract receivable resulting from the sale of assets acquired in the liquidation of loans and loans to non-members.',</br>

 'Acct_002': 'Leases Receivable. Include the rate, number, and dollar amount of outstanding direct financing leases as defined by GAAP (credit union is lessor). Credit unions that lease personal property such as vehicles to members make direct financing leases.',</br>
 
 'Acct_003': 'Loans Held for Sale. Report the amount of outstanding loans either identified for sale at origination or subsequently for which there has been a decision to sell. Loans held for Sale should not be included in the amounts reported under the Loan & Leases section lines 15 through 22.',</br>
 
 'Acct_007': 'Land and building, less depreciation on building, if any.',</br>
 
 'Acct_008': 'All other fixed assets such as furniture and fixtures, and leasehold improvements, less related depreciation, if any.  In addition, include leased assets under capital lease (credit union is lessee), less accumulated depreciation, if any.  In this situation, the credit union is leasing assets and granted a lease from an outside entity.',</br>
 
 'Acct_009': 'Include prepaid expenses, accounts receivable, accrued income on loans and investments, etc.  In addition, include direct financing leases, (credit union is lessor).  Credit unions that lease personal property such as vehicles to members make direct financing leases.  In this situation, the credit union is granting a lease to the member.',</br>
 
 'Acct_009A': 'Other Assets, Accrued Interest on Loans.',</br>
 
 'Acct_009B': 'Other Assets, Accrued Interest on Investments.',</br>
 
 'Acct_009C': 'Other Assets, All Other.',</br>
 
 'Acct_009D': 'Total Intangible Assets',</br>
 
 'Acct_009D1': 'Identifiable Intangible Assets',</br>
 
 'Acct_009D2': 'Goodwill',</br>
 
 'Acct_009E': 'Non-Trading Derivative Assets',</br>
 
 'Acct_010': 'TOTAL ASSETS'}..ect</br>

# 7. Load FS220 Files

In [553]:
log = logging.getLogger(__name__)

def _read_txt_with_enc_fallback(path: Path) -> pd.DataFrame:
    """Try UTF-8, then cp1252, then latin1."""
    for enc in ("utf-8", "cp1252", "latin1"):
        try:
            df = pd.read_csv(path, encoding=enc)  
            log.info("Loaded %s (encoding=%s, shape=%s)", path.name, enc, df.shape)
            return df
        except UnicodeDecodeError:
            continue
    # last resort: replace bad bytes
    df = pd.read_csv(path, encoding="utf-8", encoding_errors="replace")
    log.info("Loaded %s (encoding=utf-8 with replacement, shape=%s)", path.name, df.shape)
    return df

def load_fs220_files(
    data_dir: str | Path,
    subfolder: str | Path,
    base_name: str = "FS220",
    suffixes: list[str] | None = None,
) -> dict[str, pd.DataFrame]:
    """
    Load FS220*.txt files into a dict of DataFrames.

    Returns a dict mapping variable-like names to DataFrames, e.g.:
      {'fs220': df, 'fs220_a': dfA, ...}
    """
    root = Path(data_dir) / subfolder
    suffixes = [""] if not suffixes else suffixes

    out: dict[str, pd.DataFrame] = {}
    for suf in suffixes:
        filename = f"{base_name}{suf}.txt" if suf else f"{base_name}.txt"
        path = root / filename
        name = (f"{base_name.lower()}_{suf.lower()}" if suf else base_name.lower())

        if not path.exists():
            log.warning("File not found: %s", path)
            continue

        try:
            out[name] = _read_txt_with_enc_fallback(path)
        except Exception as e:
            log.error("Failed to load %s: %s", path, e)
            continue

    return out

# 8. Convert All keys/accounts in the description file to lower case 
### ACCT001----> acct001 Acct005---->acct005

In [554]:
def lower_desc_map_from_dict(acct_desc: dict[str, str]) -> dict[str, str]:
    return {str(k).strip().lower(): v for k, v in acct_desc.items()}

In [555]:
desc_map_lc = lower_desc_map_from_dict (acct_map)

In [556]:
len(desc_map_lc.keys())

1212

# 9. Normalize Column Names

## 9. a Convert All Target IDs into Upper Case

In [557]:
def normalize_id_columns(df, targets=("CU_NUMBER","CYCLE_DATE","JOIN_NUMBER")):
    """
    Force just the target ID columns to uppercase (if present), leave others intact.
    
    """
    targets = set(targets)
    df.columns = [c.upper() if c.upper() in targets else c for c in df.columns]
    return df

## 9. b Add Description To Account Numbers (acct_002 Amount of Leases Receivable)

In [558]:
def annotate_fs220_active(
    df: pd.DataFrame,
    active_acct_dict: dict[str, str],  # {account_code: description} for ACTIVE only
    id_cols: tuple[str, ...] = ("CU_NUMBER", "CYCLE_DATE", "JOIN_NUMBER"),
    annotate_fmt: str = "{col} {desc}"              
) -> pd.DataFrame:
    """
    Filter df to ID columns + ACTIVE account columns (per active_acct_dict),
    and rename those active columns by appending their description.

    - Matching is case-insensitive on the account code (column name).
    - ID columns are preserved as-is.
    """
    # case-insensitive lookup for active accounts
    active_map_lc = {str(k).strip().lower(): v for k, v in active_acct_dict.items()}

    id_set = set(id_cols)

    # Keep only IDs + columns that are in the active account dictionary
    keep_cols = [c for c in df.columns if (c in id_set) or (str(c).strip().lower() in active_map_lc)]
    out = df[keep_cols].copy()


    rename = {}
    for c in out.columns:
        if c in id_set:
            continue
        desc = active_map_lc.get(str(c).strip().lower())
        if desc:  # only annotate when we have a description
            rename[c] = annotate_fmt.format(col=c, desc=desc)

    if rename:
        out.rename(columns=rename, inplace=True)

    return out

# March 2024

In [559]:
SUBFOLDER = "call-report-data-2024-03" # March
SUFFIXES = ["", "A", "B", "C", "D", "G", "H", "I", "J", "K", "L", "M", "N", "P", "Q", "R", "S"]

fs220_dataframes = load_fs220_files(DATA_DIR, SUBFOLDER, base_name="FS220", suffixes=SUFFIXES)

INFO:__main__:Loaded FS220.txt (encoding=utf-8, shape=(4670, 246))
INFO:__main__:Loaded FS220A.txt (encoding=utf-8, shape=(4670, 249))
INFO:__main__:Loaded FS220B.txt (encoding=utf-8, shape=(4670, 250))
INFO:__main__:Loaded FS220C.txt (encoding=utf-8, shape=(4670, 250))
INFO:__main__:Loaded FS220D.txt (encoding=cp1252, shape=(4670, 230))
INFO:__main__:Loaded FS220G.txt (encoding=utf-8, shape=(4670, 252))
INFO:__main__:Loaded FS220H.txt (encoding=utf-8, shape=(4670, 249))
INFO:__main__:Loaded FS220I.txt (encoding=utf-8, shape=(4670, 251))
INFO:__main__:Loaded FS220J.txt (encoding=utf-8, shape=(4670, 255))
INFO:__main__:Loaded FS220K.txt (encoding=utf-8, shape=(4670, 148))
INFO:__main__:Loaded FS220L.txt (encoding=utf-8, shape=(4670, 243))
INFO:__main__:Loaded FS220M.txt (encoding=utf-8, shape=(4670, 70))
INFO:__main__:Loaded FS220N.txt (encoding=utf-8, shape=(4670, 81))
INFO:__main__:Loaded FS220P.txt (encoding=utf-8, shape=(4670, 193))
INFO:__main__:Loaded FS220Q.txt (encoding=utf-8, shape=(4670, 203))
INFO:__main__:Loaded FS220R.txt (encoding=utf-8, shape=(4670, 231))
INFO:__main__:Loaded FS220S.txt (encoding=utf-8, shape=(4670, 30))

In [560]:
for name, df in fs220_dataframes.items():
    fs220_dataframes[name] = normalize_id_columns(df)

In [561]:
cleaned = {}
for name, df in fs220_dataframes.items():  
    cleaned[name] = annotate_fs220_active(df, desc_map_lc)

# Join All March Datasets From All FS220 Files

In [562]:
def prep_index(df):
    return (df
            .assign(CYCLE_DATE=pd.to_datetime(df['CYCLE_DATE']).dt.date)
            .set_index(['CU_NUMBER','CYCLE_DATE','JOIN_NUMBER'])
            .sort_index())

frames_idx = [prep_index(df) for df in cleaned.values()]
combined_wide_march = reduce(lambda L, R: L.join(R, how='outer', rsuffix='_dup'), frames_idx).reset_index()

In [563]:
combined_wide_march.shape

(4670, 1215)

In [564]:
combined_wide_march.head()

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_007 Land and Building,ACCT_008 Other Fixed Assets,ACCT_010 TOTAL ASSETS,ACCT_013 Total Amount of Shares,ACCT_018 Total Amount of Shares and Deposits,ACCT_021B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 2 to less than 6 months delinquent,ACCT_022B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 6 to less than 12 months delinquent,ACCT_023B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 12 months and over delinquent,ACCT_025A Total number of Loans and Leases,ACCT_025B Total amount of Loans and Leases,ACCT_031A Loans Granted Year-to-Date,ACCT_031B Amount of Loans Granted Year-to-Date,ACCT_041B Total Amount of Delinquent Loans & Leases (Two or more months),"ACCT_058C Borrowing Repurchase Transactions, Total Amount",ACCT_083 Number of current members (not number of accounts),ACCT_084 Number of potential members,ACCT_300 Provision for Loan & Lease Losses,ACCT_340 Interest on Borrowed Money,ACCT_380 Dividends on Shares (Includes dividends earned during current period),ACCT_457 Non-Member Deposits,ACCT_521 Interest Rate of Unsecured Credit Card Loans,ACCT_522 Interest Rate of All Other Unsecured Loans/Lines of Credit,ACCT_523 Interest Rate of New Vehicle Loans,ACCT_524 Interest Rate of Used Vehicle Loans,ACCT_550 Total Amount of All Loans Charged Off Year-to-Date,ACCT_551 Total Amount of All Year-to-Date Recoveries on Charged-Off Loans,ACCT_602 Net Income (unless the amount is already included in Undivided Earnings),ACCT_630 Total Amount of All Other Shares,ACCT_657 Amount of Regular Shares,ACCT_658 Other Reserves (Appropriations for Undivided Earnings),ACCT_668 Appropriation for Non-Conforming Investments (SCU ONLY),ACCT_671 Total Non-Interest Expense (Sum of items 18-27),ACCT_719 Less: Allowance for Loan & Lease Losses,ACCT_794 NCUA Share Insurance Capitalization Deposit,ACCT_825 Accounts Payable and Other Liabilities,ACCT_860C Total Borrowings,ACCT_880 Total Amount of Non-Member Deposits,ACCT_902 Amount of Share Drafts,ACCT_906A IRA/KEOGH Accounts - < 1 Year,ACCT_908A Share Certificates - < 1 Year,ACCT_908C Total Amount of Share Certificates,ACCT_911 Total Amount of Money Market Shares,ACCT_940 Undivided Earnings,ACCT_968 Number of Used Vehicle Loans,ACCT_020B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 1 month to less than 2 months delinquent,ACCT_024B Amount of Delinquent Unsecured Credit Card Loans as of - 1 month to less than 2 months delinquent.,ACCT_400A Net Member Business Loan Balance,...,ACCT_SL0020 Number of Outstanding Loans Purchased from Other Sources,ACCT_SL0021 Amount of Outstanding Loans Purchased from Other Sources,"ACCT_SL0022 Number of Loans Sold, Year-to-date","ACCT_SL0023 Amount of Loans Sold, Year-to-date","ACCT_SL0024 Number of First Mortgage loans sold on the secondary market, Year-to-date","ACCT_SL0026 Number of Loans Transferred with Limited Recourse Qualifying for Sales Accounting, Year-to-date","ACCT_SL0028 Number of Real Estate Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0029 Amount of Real Estate Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0030 Number of Outstanding Real Estate Loans Sold with Servicing Retained,"ACCT_SL0032 Number of All Other Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0033 Amount of All Other Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0034 Number of Outstanding All Other Loans Sold with Servicing Retained,ACCT_SL0035 Amount of Outstanding All Other Loans Sold with Servicing Retained,ACCT_LR0001 CCULR Election to opt into the Complex Credit Union Leverage Ratio,ACCT_LR0002 CCULR Off-Balance sheet exposures,ACCT_LR0003 CCULR Off-Balance sheet exposures ratio,ACCT_LR0004 CCULR Trading Assets and Trading Liabilities,ACCT_LR0005 CCULR Trading Assets and Trading Liabilities Ratio,ACCT_LR0006 CCULR Goodwill and Other Intangible Assets,ACCT_LR0007 CCULR Goodwill and Other Intangible Assets Ratio,ACCT_LR0008 Complex Credit Union Leverage Ratio Grace Period Indicator,ACCT_LQ0060 Borrowing Arrangements - Total Borrowing Capacity at Central Liquidity Facility,ACCT_LQ0061 Borrowing Arrangements - Total Borrowing Capacity at Federal Reserve Bank,ACCT_LQ0062 Borrowing Arrangements - Total Borrowing Capacity at FRB Paycheck Protrection Program Lending Facility,ACCT_NW0004 CECL Transition Provision (as determined under 702.703(c)),ACCT_PG0001 Legal Entity Identifier (LEI),ACCT_PG0002 Anti-money laundering monitoring system,ACCT_PP0037 Does the CU use financial technology companies to provide member services?,ACCT_PP0038 Auto Lending,ACCT_PP0039 Mortgage Lending,ACCT_PP0040 Secured personal loans,ACCT_PP0041 Unsecured personal loans,ACCT_PP0042 Lead generation for new members,ACCT_PP0043 Lead generation for share accounts,ACCT_PP0044 Acquire participation loans,ACCT_PP0045 Person-to-Person payments,ACCT_PP0046 Investment security exchange services,ACCT_PP0047 Communication,ACCT_PP0048 FinTech-Other,ACCT_PP0049 Does the CU offer cryptocurrency services to members,ACCT_PP0050 Exchange services,ACCT_PP0051 Non-custodial wallets,ACCT_PP0052 Custodial wallets,ACCT_PP0055 Mobile application,ACCT_PP0056 Crypto-Other,ACCT_PP0057 Does the CU use blockchain or distributed ledger technology?,ACCT_PR0001 Located in Metropolitan Statistical Area (MSA),ACCT_PR0002 home purchase loan or refinanced a home purchase loan,ACCT_PR0003 Originated closed-end mortgages in each of the two preceding calendar years or originated open-end lines of credit in each of the two preceding calendar years in excess of the HMDA Loan-Volume Threshold?,ACCT_PR0004 Date of HMDA LAR filing
0,1,2024-03-31,2,42402,7458,11182372,9856392,9856392,46439,478,0,767,8953804,31,720671,69523,0,1276,2000,0,0,32327,0,0.0,925.0,674.0,674.0,6519,696,29922,88074,6715796,203071,0,95898,0,108220,3541,0,0,560275,0,432472,2492247,0,1089446,242,109124,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5025,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,6,2024-03-31,7,2926739,1436871,275381898,208672795,241409795,1111383,826955,93026,20300,194154396,1090,14248221,2720931,0,28945,70000,0,112,788080,32737,1074.0,1184.0,500.0,666.0,367890,115903,0,275698,121112510,0,0,3628514,0,2060044,6123939,7000000,32737000,44353402,5606112,26271750,33188394,3146322,22876865,3180,4048995,682511,911272,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493006GFSNOUCCL1W91,Combination,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 20 2024 6:00AM
2,12,2024-03-31,11,5004004,555306,61526262,56663797,56663797,152053,2677,0,8001,27050615,609,2777539,247781,0,9133,19133,0,15588,85617,0,1243.0,1050.0,800.0,875.0,206482,30395,0,379808,26235674,0,0,1201434,0,551490,338825,0,0,16494290,911196,2076990,2956147,9388928,5867901,345,169765,27425,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,254900TYE85Q9OTQ5038,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Dec 31 2023 5:00AM
3,13,2024-03-31,12,12889552,665915,1058083728,842713968,919926247,849774,962009,0,35885,933368458,7449,99199184,2662923,0,65941,849530,0,542312,6944265,22,950.0,950.0,364.0,364.0,769471,201614,0,234783,172985942,0,0,6030987,0,7623047,8080746,45000000,77212279,120559248,32447859,215171696,444148170,19807926,86176916,12220,15501991,91847,0,...,0,0,0,0,0,0,0,0,235,0,0,0,0,1,108265946,1023,0,0,0,0,0,220000000,0,0,1526418,549300U18MOAH5F95P15,Automated,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 14 2024 6:00AM
4,16,2024-03-31,14,0,1893,9656630,8380331,8380331,0,529,16340,280,3901475,14,239962,16869,0,900,1320,0,45,10053,0,1490.0,850.0,624.0,699.0,21311,183,0,0,4977160,479074,0,92646,28574,84714,-11816,0,0,2141669,193129,1068371,1068371,0,795347,70,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Manual,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN

# June 2024

In [565]:
SUBFOLDER = "call-report-data-2024-06" # June
SUFFIXES = ["", "A", "B", "C", "D", "G", "H", "I", "J", "K", "L", "M", "N", "P", "Q", "R", "S"]

fs220_dataframes_june = load_fs220_files(DATA_DIR, SUBFOLDER, base_name="FS220", suffixes=SUFFIXES)

INFO:__main__:Loaded FS220.txt (encoding=utf-8, shape=(4631, 246))
INFO:__main__:Loaded FS220A.txt (encoding=utf-8, shape=(4631, 249))
INFO:__main__:Loaded FS220B.txt (encoding=utf-8, shape=(4631, 250))
INFO:__main__:Loaded FS220C.txt (encoding=utf-8, shape=(4631, 250))
INFO:__main__:Loaded FS220D.txt (encoding=cp1252, shape=(4631, 230))
INFO:__main__:Loaded FS220G.txt (encoding=utf-8, shape=(4631, 252))
INFO:__main__:Loaded FS220H.txt (encoding=utf-8, shape=(4631, 249))
INFO:__main__:Loaded FS220I.txt (encoding=utf-8, shape=(4631, 251))
INFO:__main__:Loaded FS220J.txt (encoding=utf-8, shape=(4631, 255))
INFO:__main__:Loaded FS220K.txt (encoding=utf-8, shape=(4631, 148))
INFO:__main__:Loaded FS220L.txt (encoding=utf-8, shape=(4631, 243))
INFO:__main__:Loaded FS220M.txt (encoding=utf-8, shape=(4631, 70))
INFO:__main__:Loaded FS220N.txt (encoding=utf-8, shape=(4631, 81))
INFO:__main__:Loaded FS220P.txt (encoding=utf-8, shape=(4631, 193))
INFO:__main__:Loaded FS220Q.txt (encoding=utf-8, shape=(4631, 203))
INFO:__main__:Loaded FS220R.txt (encoding=utf-8, shape=(4631, 231))
INFO:__main__:Loaded FS220S.txt (encoding=utf-8, shape=(4631, 30))

In [566]:
for name, df in fs220_dataframes_june.items():
    fs220_dataframes_june[name] = normalize_id_columns(df)

In [567]:
cleaned_june = {}
for name, df in fs220_dataframes_june.items():  
    cleaned_june[name] = annotate_fs220_active(df, desc_map_lc)

# Join All June Datasets From All FS220 Files

In [568]:
def prep_index(df):
    return (df
            .assign(CYCLE_DATE=pd.to_datetime(df['CYCLE_DATE']).dt.date)
            .set_index(['CU_NUMBER','CYCLE_DATE','JOIN_NUMBER'])
            .sort_index())

frames_idx_june = [prep_index(df) for df in cleaned_june.values()]
combined_wide_june = reduce(lambda L, R: L.join(R, how='outer', rsuffix='_dup'), frames_idx_june).reset_index()

In [569]:
combined_wide_june

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_007 Land and Building,ACCT_008 Other Fixed Assets,ACCT_010 TOTAL ASSETS,ACCT_013 Total Amount of Shares,ACCT_018 Total Amount of Shares and Deposits,ACCT_021B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 2 to less than 6 months delinquent,ACCT_022B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 6 to less than 12 months delinquent,ACCT_023B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 12 months and over delinquent,ACCT_025A Total number of Loans and Leases,ACCT_025B Total amount of Loans and Leases,ACCT_031A Loans Granted Year-to-Date,ACCT_031B Amount of Loans Granted Year-to-Date,ACCT_041B Total Amount of Delinquent Loans & Leases (Two or more months),"ACCT_058C Borrowing Repurchase Transactions, Total Amount",ACCT_083 Number of current members (not number of accounts),ACCT_084 Number of potential members,ACCT_300 Provision for Loan & Lease Losses,ACCT_340 Interest on Borrowed Money,ACCT_380 Dividends on Shares (Includes dividends earned during current period),ACCT_457 Non-Member Deposits,ACCT_521 Interest Rate of Unsecured Credit Card Loans,ACCT_522 Interest Rate of All Other Unsecured Loans/Lines of Credit,ACCT_523 Interest Rate of New Vehicle Loans,ACCT_524 Interest Rate of Used Vehicle Loans,ACCT_550 Total Amount of All Loans Charged Off Year-to-Date,ACCT_551 Total Amount of All Year-to-Date Recoveries on Charged-Off Loans,ACCT_602 Net Income (unless the amount is already included in Undivided Earnings),ACCT_630 Total Amount of All Other Shares,ACCT_657 Amount of Regular Shares,ACCT_658 Other Reserves (Appropriations for Undivided Earnings),ACCT_668 Appropriation for Non-Conforming Investments (SCU ONLY),ACCT_671 Total Non-Interest Expense (Sum of items 18-27),ACCT_719 Less: Allowance for Loan & Lease Losses,ACCT_794 NCUA Share Insurance Capitalization Deposit,ACCT_825 Accounts Payable and Other Liabilities,ACCT_860C Total Borrowings,ACCT_880 Total Amount of Non-Member Deposits,ACCT_902 Amount of Share Drafts,ACCT_906A IRA/KEOGH Accounts - < 1 Year,ACCT_908A Share Certificates - < 1 Year,ACCT_908C Total Amount of Share Certificates,ACCT_911 Total Amount of Money Market Shares,ACCT_940 Undivided Earnings,ACCT_968 Number of Used Vehicle Loans,ACCT_020B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 1 month to less than 2 months delinquent,ACCT_024B Amount of Delinquent Unsecured Credit Card Loans as of - 1 month to less than 2 months delinquent.,ACCT_400A Net Member Business Loan Balance,...,ACCT_SL0020 Number of Outstanding Loans Purchased from Other Sources,ACCT_SL0021 Amount of Outstanding Loans Purchased from Other Sources,"ACCT_SL0022 Number of Loans Sold, Year-to-date","ACCT_SL0023 Amount of Loans Sold, Year-to-date","ACCT_SL0024 Number of First Mortgage loans sold on the secondary market, Year-to-date","ACCT_SL0026 Number of Loans Transferred with Limited Recourse Qualifying for Sales Accounting, Year-to-date","ACCT_SL0028 Number of Real Estate Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0029 Amount of Real Estate Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0030 Number of Outstanding Real Estate Loans Sold with Servicing Retained,"ACCT_SL0032 Number of All Other Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0033 Amount of All Other Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0034 Number of Outstanding All Other Loans Sold with Servicing Retained,ACCT_SL0035 Amount of Outstanding All Other Loans Sold with Servicing Retained,ACCT_LR0001 CCULR Election to opt into the Complex Credit Union Leverage Ratio,ACCT_LR0002 CCULR Off-Balance sheet exposures,ACCT_LR0003 CCULR Off-Balance sheet exposures ratio,ACCT_LR0004 CCULR Trading Assets and Trading Liabilities,ACCT_LR0005 CCULR Trading Assets and Trading Liabilities Ratio,ACCT_LR0006 CCULR Goodwill and Other Intangible Assets,ACCT_LR0007 CCULR Goodwill and Other Intangible Assets Ratio,ACCT_LR0008 Complex Credit Union Leverage Ratio Grace Period Indicator,ACCT_LQ0060 Borrowing Arrangements - Total Borrowing Capacity at Central Liquidity Facility,ACCT_LQ0061 Borrowing Arrangements - Total Borrowing Capacity at Federal Reserve Bank,ACCT_LQ0062 Borrowing Arrangements - Total Borrowing Capacity at FRB Paycheck Protrection Program Lending Facility,ACCT_NW0004 CECL Transition Provision (as determined under 702.703(c)),ACCT_PG0001 Legal Entity Identifier (LEI),ACCT_PG0002 Anti-money laundering monitoring system,ACCT_PP0037 Does the CU use financial technology companies to provide member services?,ACCT_PP0038 Auto Lending,ACCT_PP0039 Mortgage Lending,ACCT_PP0040 Secured personal loans,ACCT_PP0041 Unsecured personal loans,ACCT_PP0042 Lead generation for new members,ACCT_PP0043 Lead generation for share accounts,ACCT_PP0044 Acquire participation loans,ACCT_PP0045 Person-to-Person payments,ACCT_PP0046 Investment security exchange services,ACCT_PP0047 Communication,ACCT_PP0048 FinTech-Other,ACCT_PP0049 Does the CU offer cryptocurrency services to members,ACCT_PP0050 Exchange services,ACCT_PP0051 Non-custodial wallets,ACCT_PP0052 Custodial wallets,ACCT_PP0055 Mobile application,ACCT_PP0056 Crypto-Other,ACCT_PP0057 Does the CU use blockchain or distributed ledger technology?,ACCT_PR0001 Located in Metropolitan Statistical Area (MSA),ACCT_PR0002 home purchase loan or refinanced a home purchase loan,ACCT_PR0003 Originated closed-end mortgages in each of the two preceding calendar years or originated open-end lines of credit in each of the two preceding calendar years in excess of the HMDA Loan-Volume Threshold?,ACCT_PR0004 Date of HMDA LAR filing
0,1,2024-06-30,2,41973,6177,11109125,9758484,9758484,0,390,0,769,8821970,199,1527573,8225,0,1259,2000,0,0,68063,0,0.0,925.0,674.0,674.0,13734,1017,48799,93430,6535109,203071,0,196035,0,97518,9325,0,0,529452,0,705016,2600493,0,1089446,245,65136,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5025,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,6,2024-06-30,7,2905322,1434630,274014841,206524238,239261238,898999,1222396,90375,20225,194109534,2253,30027409,3207094,0,28845,70000,0,2200,1658310,32737,1072.0,1202.0,517.0,685.0,964204,287676,0,270034,116409508,0,0,7299810,0,2309148,6918342,7000000,32737000,42725165,5503732,28540338,37607045,2922008,22630950,3149,2338177,548128,1400317,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493006GFSNOUCCL1W91,Combination,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 20 2024 6:00AM
2,12,2024-06-30,11,4962391,516420,60169418,55132588,55132588,123439,4778,0,7974,27695075,1602,6964412,205748,0,9073,19073,0,15588,176277,0,1243.0,1050.0,800.0,875.0,297617,63961,91919,280930,25051362,0,0,2365075,0,516955,272119,0,0,16008084,882561,2347306,3254561,9318251,5972179,346,230950,24644,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,254900TYE85Q9OTQ5038,Manual,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Dec 31 2023 5:00AM
3,13,2024-06-30,12,15951621,615456,1074739920,849427072,926710410,843264,579338,280277,36758,977889001,10475,221770335,3527789,0,66652,849530,0,1086553,14185864,21,950.0,950.0,364.0,364.0,1542660,340640,0,237770,171198693,0,0,12021058,0,8037974,9291366,51000000,77283338,115907248,30556469,223702748,454756109,21695623,88832090,12510,13515875,69159,0,...,0,0,0,0,0,0,0,0,233,0,0,0,0,1,109750158,1021,0,0,0,0,0,225000000,0,0,1526418,549300U18MOAH5F95P15,Automated,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 14 2024 6:00AM
4,16,2024-06-30,14,0,1602,9617599,8334581,8334581,0,529,15437,276,3816079,29,516272,15966,0,886,1320,0,45,23459,0,1490.0,950.0,649.0,724.0,21311,1080,0,0,5117127,479074,0,182804,28874,80311,-13200,0,0,1862280,186093,1169079,1169079,0,796838,74,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Manual,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4626,97108,2024-06-30,14738,0,155931,66460005,60938040,60938040,15912,0,0,72273,43900214,90,4430289,85388,0,2656,3895000,0,321,707180,0,1294.0,1200.0,625.0,800.0,63749,19476,-85217,0,19882226,0,0,809757,0,0,103085,0,0,4400178,1205026,9373926,27955773,4927913,6407836,53759,79770,581,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,207700,NaN,Automated,1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,0,0,0,0,1.0,1.0,NaN,NaN
4627,97109,2024-06-30,2759,6321093,545736,470938640,399798930,399798930,848028,188440,108,18647,362790254,1834,48698747,2044239,0,25905,500000,0,367831,3988629,0,1450.0,1349.0,750.0,860.0,725079,222334,1692355,5877753,111588403,0,0,6958610,0,0,4152952,20797100,0,75960283,15714843,87573034,114591037,70141273,45165904,5954,2464471,96940,42729566,...,0,0,6,463785,0,0,6,329315,78,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493001D5DXR1S70P689,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 3 2024 5:00AM
4628,97110,2024-06-30,17502,14942643,747189,374622068,337601619,337851619,623472,885346,183002,13804,269680844,1213,28798233,2325238,0,24747,255994,0,26794,2971782,1,1699.0,1324.0,724.0,849.0,673300,76060,864853,7271132,65245357,0,0,6994466,0,0,5689834,0,250000,73746642,8272669,75480140,89180875,90426791,28390133,2500,3050757,81796,8935839,...,0,0,7,1949700,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7370080,0,720317,NaN,Combination,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4629,97111,2024-06-30,21049,4041035,642177,164782804,147412044,147412044,139608,12793,0,7943,122734916,1146,22075149,1314287,0,13007,900000,0,97073,1175986,0,1263.0,1009.0,555.0,711.0,205513,60723,0,198136,54053865,0,0,2881900,0,0,419588,7000000,0,28761859,5496124,38273648,44275486,13434622,11944963,2818,570061,20753,37822021,...,52,4486703,5,925551,5,0,0,0,6,0,0,2,328165,0,0,0,0,0,0,0,0,0,0,0,0,549300N1MCHMZQ2BP498,Combination,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 19 2024 5:00AM
4630,97112,2024-06-30,22698,8109676,493517,234289507,222949875,222949875,280815,106410,0,11446,129737899,971,18982151,1075536,0,21277,3600578,0,6,1428276,0,832.0,898.0,502.0,559.0,521522,58674,0,0,96406037,0,0,4343599,0,0,1484734,0,0,50311195,11865876,39866581,52894141,9818150,26813621,3513,2333196,134855,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,NaN,NaN,NaN

# September 2024

In [570]:
SUBFOLDER = "call-report-data-2024-09" # September
SUFFIXES = ["", "A", "B", "C", "D", "G", "H", "I", "J", "K", "L", "M", "N", "P", "Q", "R", "S"]

fs220_dataframes_sep = load_fs220_files(DATA_DIR, SUBFOLDER, base_name="FS220", suffixes=SUFFIXES)

INFO:__main__:Loaded FS220.txt (encoding=utf-8, shape=(4596, 246))
INFO:__main__:Loaded FS220A.txt (encoding=utf-8, shape=(4596, 249))
INFO:__main__:Loaded FS220B.txt (encoding=utf-8, shape=(4596, 250))
INFO:__main__:Loaded FS220C.txt (encoding=utf-8, shape=(4596, 250))
INFO:__main__:Loaded FS220D.txt (encoding=cp1252, shape=(4596, 230))
INFO:__main__:Loaded FS220G.txt (encoding=utf-8, shape=(4596, 252))
INFO:__main__:Loaded FS220H.txt (encoding=utf-8, shape=(4596, 249))
INFO:__main__:Loaded FS220I.txt (encoding=utf-8, shape=(4596, 251))
INFO:__main__:Loaded FS220J.txt (encoding=utf-8, shape=(4596, 255))
INFO:__main__:Loaded FS220K.txt (encoding=utf-8, shape=(4596, 148))
INFO:__main__:Loaded FS220L.txt (encoding=utf-8, shape=(4596, 243))
INFO:__main__:Loaded FS220M.txt (encoding=utf-8, shape=(4596, 70))
INFO:__main__:Loaded FS220N.txt (encoding=utf-8, shape=(4596, 81))
INFO:__main__:Loaded FS220P.txt (encoding=utf-8, shape=(4596, 193))
INFO:__main__:Loaded FS220Q.txt (encoding=utf-8, shape=(4596, 203))
INFO:__main__:Loaded FS220R.txt (encoding=utf-8, shape=(4596, 231))
INFO:__main__:Loaded FS220S.txt (encoding=utf-8, shape=(4596, 30))

In [571]:
# Convert ID columns into uppercase
for name, df in fs220_dataframes_sep.items():
    fs220_dataframes_sep[name] = normalize_id_columns(df)

# add description to column names
cleaned_sep = {}
for name, df in fs220_dataframes_sep.items():  
    cleaned_sep[name] = annotate_fs220_active(df, desc_map_lc)

# Join FS220 September

In [572]:
def prep_index(df):
    return (df
            .assign(CYCLE_DATE=pd.to_datetime(df['CYCLE_DATE']).dt.date)
            .set_index(['CU_NUMBER','CYCLE_DATE','JOIN_NUMBER'])
            .sort_index())


frames_idx_sep = [prep_index(df) for df in cleaned_sep.values()]
combined_wide_sep = reduce(lambda L, R: L.join(R, how='outer', rsuffix='_dup'), frames_idx_sep).reset_index()

In [573]:
combined_wide_sep

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_007 Land and Building,ACCT_008 Other Fixed Assets,ACCT_010 TOTAL ASSETS,ACCT_013 Total Amount of Shares,ACCT_018 Total Amount of Shares and Deposits,ACCT_021B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 2 to less than 6 months delinquent,ACCT_022B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 6 to less than 12 months delinquent,ACCT_023B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 12 months and over delinquent,ACCT_025A Total number of Loans and Leases,ACCT_025B Total amount of Loans and Leases,ACCT_031A Loans Granted Year-to-Date,ACCT_031B Amount of Loans Granted Year-to-Date,ACCT_041B Total Amount of Delinquent Loans & Leases (Two or more months),"ACCT_058C Borrowing Repurchase Transactions, Total Amount",ACCT_083 Number of current members (not number of accounts),ACCT_084 Number of potential members,ACCT_300 Provision for Loan & Lease Losses,ACCT_340 Interest on Borrowed Money,ACCT_380 Dividends on Shares (Includes dividends earned during current period),ACCT_457 Non-Member Deposits,ACCT_521 Interest Rate of Unsecured Credit Card Loans,ACCT_522 Interest Rate of All Other Unsecured Loans/Lines of Credit,ACCT_523 Interest Rate of New Vehicle Loans,ACCT_524 Interest Rate of Used Vehicle Loans,ACCT_550 Total Amount of All Loans Charged Off Year-to-Date,ACCT_551 Total Amount of All Year-to-Date Recoveries on Charged-Off Loans,ACCT_602 Net Income (unless the amount is already included in Undivided Earnings),ACCT_630 Total Amount of All Other Shares,ACCT_657 Amount of Regular Shares,ACCT_658 Other Reserves (Appropriations for Undivided Earnings),ACCT_668 Appropriation for Non-Conforming Investments (SCU ONLY),ACCT_671 Total Non-Interest Expense (Sum of items 18-27),ACCT_719 Less: Allowance for Loan & Lease Losses,ACCT_794 NCUA Share Insurance Capitalization Deposit,ACCT_825 Accounts Payable and Other Liabilities,ACCT_860C Total Borrowings,ACCT_880 Total Amount of Non-Member Deposits,ACCT_902 Amount of Share Drafts,ACCT_906A IRA/KEOGH Accounts - < 1 Year,ACCT_908A Share Certificates - < 1 Year,ACCT_908C Total Amount of Share Certificates,ACCT_911 Total Amount of Money Market Shares,ACCT_940 Undivided Earnings,ACCT_968 Number of Used Vehicle Loans,ACCT_020B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 1 month to less than 2 months delinquent,ACCT_024B Amount of Delinquent Unsecured Credit Card Loans as of - 1 month to less than 2 months delinquent.,ACCT_400A Net Member Business Loan Balance,...,ACCT_SL0020 Number of Outstanding Loans Purchased from Other Sources,ACCT_SL0021 Amount of Outstanding Loans Purchased from Other Sources,"ACCT_SL0022 Number of Loans Sold, Year-to-date","ACCT_SL0023 Amount of Loans Sold, Year-to-date","ACCT_SL0024 Number of First Mortgage loans sold on the secondary market, Year-to-date","ACCT_SL0026 Number of Loans Transferred with Limited Recourse Qualifying for Sales Accounting, Year-to-date","ACCT_SL0028 Number of Real Estate Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0029 Amount of Real Estate Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0030 Number of Outstanding Real Estate Loans Sold with Servicing Retained,"ACCT_SL0032 Number of All Other Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0033 Amount of All Other Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0034 Number of Outstanding All Other Loans Sold with Servicing Retained,ACCT_SL0035 Amount of Outstanding All Other Loans Sold with Servicing Retained,ACCT_LR0001 CCULR Election to opt into the Complex Credit Union Leverage Ratio,ACCT_LR0002 CCULR Off-Balance sheet exposures,ACCT_LR0003 CCULR Off-Balance sheet exposures ratio,ACCT_LR0004 CCULR Trading Assets and Trading Liabilities,ACCT_LR0005 CCULR Trading Assets and Trading Liabilities Ratio,ACCT_LR0006 CCULR Goodwill and Other Intangible Assets,ACCT_LR0007 CCULR Goodwill and Other Intangible Assets Ratio,ACCT_LR0008 Complex Credit Union Leverage Ratio Grace Period Indicator,ACCT_LQ0060 Borrowing Arrangements - Total Borrowing Capacity at Central Liquidity Facility,ACCT_LQ0061 Borrowing Arrangements - Total Borrowing Capacity at Federal Reserve Bank,ACCT_LQ0062 Borrowing Arrangements - Total Borrowing Capacity at FRB Paycheck Protrection Program Lending Facility,ACCT_NW0004 CECL Transition Provision (as determined under 702.703(c)),ACCT_PG0001 Legal Entity Identifier (LEI),ACCT_PG0002 Anti-money laundering monitoring system,ACCT_PP0037 Does the CU use financial technology companies to provide member services?,ACCT_PP0038 Auto Lending,ACCT_PP0039 Mortgage Lending,ACCT_PP0040 Secured personal loans,ACCT_PP0041 Unsecured personal loans,ACCT_PP0042 Lead generation for new members,ACCT_PP0043 Lead generation for share accounts,ACCT_PP0044 Acquire participation loans,ACCT_PP0045 Person-to-Person payments,ACCT_PP0046 Investment security exchange services,ACCT_PP0047 Communication,ACCT_PP0048 FinTech-Other,ACCT_PP0049 Does the CU offer cryptocurrency services to members,ACCT_PP0050 Exchange services,ACCT_PP0051 Non-custodial wallets,ACCT_PP0052 Custodial wallets,ACCT_PP0055 Mobile application,ACCT_PP0056 Crypto-Other,ACCT_PP0057 Does the CU use blockchain or distributed ledger technology?,ACCT_PR0001 Located in Metropolitan Statistical Area (MSA),ACCT_PR0002 home purchase loan or refinanced a home purchase loan,ACCT_PR0003 Originated closed-end mortgages in each of the two preceding calendar years or originated open-end lines of credit in each of the two preceding calendar years in excess of the HMDA Loan-Volume Threshold?,ACCT_PR0004 Date of HMDA LAR filing
0,1,2024-09-30,2,41544,5201,11419048,10056100,10056100,18222,0,0,775,8941424,331,2850146,41726,0,1263,2000,0,0,106588,0,0.0,925.0,674.0,674.0,23748,1547,64951,80905,6402941,203072,0,309093,0,97518,5479,0,0,560964,0,951986,3011290,0,1089446,251,80445,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5025,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,6,2024-09-30,7,2888211,826725,270329243,205667270,236421270,1067639,745656,468070,20552,199369178,3800,51705291,2880328,0,28622,70000,0,11512,2549521,30754,1069.0,1210.0,531.0,690.0,1678207,402790,0,367542,114953873,0,0,10973994,0,2309148,5541424,7014068,30754000,43477831,5543625,30406098,37402205,2796935,22345037,3210,3021228,578212,1207318,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493006GFSNOUCCL1W91,Combination,1,1,1,1,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 20 2024 6:00AM
2,12,2024-09-30,11,4917054,548121,58700838,53571526,53571526,183896,41473,0,8571,28902875,3169,11602750,269909,0,9059,19059,0,15588,274645,0,1243.0,1050.0,800.0,875.0,377994,91006,-56536,360849,24298390,0,0,3567229,0,516956,297972,0,0,14710104,821117,2294538,3649776,9357174,6141323,342,227518,20591,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,254900TYE85Q9OTQ5038,Manual,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Dec 31 2023 5:00AM
3,13,2024-09-30,12,17921895,565940,1125128209,890457449,973434627,1522428,482218,182764,37060,990240146,12740,332723000,3390419,0,67571,849530,0,1703699,21810627,22,1100.0,950.0,364.0,364.0,2423262,499692,0,234295,166568234,0,0,18575228,0,8037974,6357020,55000000,82977178,115269478,31729379,250256496,491821406,26546093,91421590,12538,17562036,134021,0,...,0,0,11,4135913,11,0,10,3952164,242,0,0,0,0,1,117664647,1045,0,0,0,0,0,215000000,0,0,1526418,549300U18MOAH5F95P15,Automated,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 14 2024 6:00AM
4,16,2024-09-30,14,0,1360,9502892,8200993,8200993,0,0,14747,278,3756830,46,835916,14747,0,885,1320,0,45,37575,0,1490.0,1000.0,649.0,674.0,21311,3489,0,0,5024453,479075,0,274796,31880,80311,-16612,0,0,1825641,186133,1164765,1164765,0,808398,76,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Manual,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4591,97109,2024-09-30,2759,6275097,549969,473080806,405391332,405391332,600856,193531,388,18626,364215358,2897,73567649,1256743,0,25792,500000,0,523115,6196002,0,1450.0,1349.0,679.0,829.0,1119933,324055,2690497,654847,106448632,0,0,10391315,0,0,4026442,14575479,0,75091174,14855256,92761536,122351116,79296720,45165904,6163,3423698,116078,43425392,...,0,0,11,816585,0,0,11,522515,82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493001D5DXR1S70P689,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 3 2024 5:00AM
4592,97110,2024-09-30,17502,14905870,755232,382663361,341412929,341412929,673967,417177,558497,13866,264452699,1787,43374436,2111767,0,24747,358435,0,26809,4405880,0,1699.0,1324.0,724.0,849.0,971164,88913,1611552,7713329,64139538,0,0,10532214,0,0,3790995,5000000,0,76475147,8531880,77333892,91111017,89986697,28390133,2412,3126906,104199,8460318,...,0,0,15,4931466,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7547147,0,720317,NaN,Combination,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4593,97111,2024-09-30,21049,4816549,611943,162826637,146556395,146556395,215836,65808,0,7900,132269057,1929,40573353,405341,0,13308,900000,0,141136,1816715,0,1263.0,1091.0,566.0,697.0,340045,86412,0,199825,52620031,0,0,4394700,0,0,549393,5000000,0,27754087,5529261,39176520,45868211,12852629,12232803,2831,966534,31974,41734988,...,51,4429124,9,1880472,8,0,1,700000,7,0,0,2,504889,0,0,0,0,0,0,0,0,0,0,0,0,549300N1MCHMZQ2BP498,Combination,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Jan 19 2024 5:00AM
4594,97112,2024-09-30,22698,8108187,464699,235450892,220660215,220660215,320049,198631,0,11371,128433323,1504,29039707,741635,0,21356,3600578,0,2743,2141423,0,831.0,919.0,517.0,579.0,788673,75779,0,0,93621065,0,0,6606027,0,0,1350697,0,0,48869816,11590483,39693366,54346217,10140643,27015368,3474,2088723,145247,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,Automated,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,NaN,NaN,NaN
4595,97113,2024-09-30,8532,679375,185046,65654324,57919281,57919281,18196,6415,0,4174,45605176,540,7442015,117677,0,8100,25000,0,90,685159,0,888.0,1050.0,540.0,603.0,208062,51765,0,5009384,18587588,0,0,1934128,0,592416,-484101,0,0,10424425,898895,9013304,10504476,12212204,8219144,858,79664,24140,937114,...,0,0,0,0,0,0,0,0,29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9505,549300snbyrug0bk5t32,Manual,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 15 2023 5:00AM

# December 2024

In [574]:
SUBFOLDER = "call-report-data-2024-12" # December
SUFFIXES = ["", "A", "B", "C", "D", "G", "H", "I", "J", "K", "L", "M", "N", "P", "Q", "R", "S"]

fs220_dataframes_dec = load_fs220_files(DATA_DIR, SUBFOLDER, base_name="FS220", suffixes=SUFFIXES)

INFO:__main__:Loaded FS220.txt (encoding=utf-8, shape=(4550, 246))
INFO:__main__:Loaded FS220A.txt (encoding=utf-8, shape=(4550, 249))
INFO:__main__:Loaded FS220B.txt (encoding=utf-8, shape=(4550, 250))
INFO:__main__:Loaded FS220C.txt (encoding=utf-8, shape=(4550, 250))
INFO:__main__:Loaded FS220D.txt (encoding=cp1252, shape=(4550, 223))
INFO:__main__:Loaded FS220G.txt (encoding=utf-8, shape=(4550, 252))
INFO:__main__:Loaded FS220H.txt (encoding=utf-8, shape=(4550, 249))
INFO:__main__:Loaded FS220I.txt (encoding=utf-8, shape=(4550, 251))
INFO:__main__:Loaded FS220J.txt (encoding=utf-8, shape=(4550, 255))
INFO:__main__:Loaded FS220K.txt (encoding=utf-8, shape=(4550, 148))
INFO:__main__:Loaded FS220L.txt (encoding=utf-8, shape=(4550, 243))
INFO:__main__:Loaded FS220M.txt (encoding=utf-8, shape=(4550, 70))
INFO:__main__:Loaded FS220N.txt (encoding=utf-8, shape=(4550, 81))
INFO:__main__:Loaded FS220P.txt (encoding=utf-8, shape=(4550, 193))
INFO:__main__:Loaded FS220Q.txt (encoding=utf-8, shape=(4550, 203))
INFO:__main__:Loaded FS220R.txt (encoding=utf-8, shape=(4550, 231))
INFO:__main__:Loaded FS220S.txt (encoding=utf-8, shape=(4550, 37))

In [575]:
# Convert ID columns into uppercase
for name, df in fs220_dataframes_dec.items():
    fs220_dataframes_dec[name] = normalize_id_columns(df)

# add description to column names
cleaned_dec = {}
for name, df in fs220_dataframes_dec.items():  
    cleaned_dec[name] = annotate_fs220_active(df, desc_map_lc)

# Join All FS220 Dec

In [576]:
def prep_index(df):
    return (df
            .assign(CYCLE_DATE=pd.to_datetime(df['CYCLE_DATE']).dt.date)
            .set_index(['CU_NUMBER','CYCLE_DATE','JOIN_NUMBER'])
            .sort_index())


frames_idx_dec = [prep_index(df) for df in cleaned_dec.values()]
combined_wide_dec = reduce(lambda L, R: L.join(R, how='outer', rsuffix='_dup'), frames_idx_dec).reset_index()

In [577]:
combined_wide_dec

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_007 Land and Building,ACCT_008 Other Fixed Assets,ACCT_010 TOTAL ASSETS,ACCT_013 Total Amount of Shares,ACCT_018 Total Amount of Shares and Deposits,ACCT_021B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 2 to less than 6 months delinquent,ACCT_022B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 6 to less than 12 months delinquent,ACCT_023B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 12 months and over delinquent,ACCT_025A Total number of Loans and Leases,ACCT_025B Total amount of Loans and Leases,ACCT_031A Loans Granted Year-to-Date,ACCT_031B Amount of Loans Granted Year-to-Date,ACCT_041B Total Amount of Delinquent Loans & Leases (Two or more months),"ACCT_058C Borrowing Repurchase Transactions, Total Amount",ACCT_083 Number of current members (not number of accounts),ACCT_084 Number of potential members,ACCT_300 Provision for Loan & Lease Losses,ACCT_340 Interest on Borrowed Money,ACCT_380 Dividends on Shares (Includes dividends earned during current period),ACCT_457 Non-Member Deposits,ACCT_521 Interest Rate of Unsecured Credit Card Loans,ACCT_522 Interest Rate of All Other Unsecured Loans/Lines of Credit,ACCT_523 Interest Rate of New Vehicle Loans,ACCT_524 Interest Rate of Used Vehicle Loans,ACCT_550 Total Amount of All Loans Charged Off Year-to-Date,ACCT_551 Total Amount of All Year-to-Date Recoveries on Charged-Off Loans,ACCT_602 Net Income (unless the amount is already included in Undivided Earnings),ACCT_630 Total Amount of All Other Shares,ACCT_657 Amount of Regular Shares,ACCT_658 Other Reserves (Appropriations for Undivided Earnings),ACCT_668 Appropriation for Non-Conforming Investments (SCU ONLY),ACCT_671 Total Non-Interest Expense (Sum of items 18-27),ACCT_719 Less: Allowance for Loan & Lease Losses,ACCT_794 NCUA Share Insurance Capitalization Deposit,ACCT_825 Accounts Payable and Other Liabilities,ACCT_860C Total Borrowings,ACCT_880 Total Amount of Non-Member Deposits,ACCT_902 Amount of Share Drafts,ACCT_906A IRA/KEOGH Accounts - < 1 Year,ACCT_908A Share Certificates - < 1 Year,ACCT_908C Total Amount of Share Certificates,ACCT_911 Total Amount of Money Market Shares,ACCT_940 Undivided Earnings,ACCT_968 Number of Used Vehicle Loans,ACCT_020B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 1 month to less than 2 months delinquent,ACCT_024B Amount of Delinquent Unsecured Credit Card Loans as of - 1 month to less than 2 months delinquent.,ACCT_400A Net Member Business Loan Balance,...,"ACCT_RL0050 Real Estate Loans reported in Account RL0047 that contractually refinance, reprice or mature within the next 5 years",ACCT_SH0013 Total Shares,ACCT_SH0018 Total Shares and Deposits,ACCT_SH0880 Total Non-Member Deposits,ACCT_SL0018 Number of Outstanding Loans Purchased from Other Financial Institutions,ACCT_SL0019 Amount of Outstanding Loans Purchased from Other Financial Institutions,ACCT_SL0020 Number of Outstanding Loans Purchased from Other Sources,ACCT_SL0021 Amount of Outstanding Loans Purchased from Other Sources,"ACCT_SL0022 Number of Loans Sold, Year-to-date","ACCT_SL0023 Amount of Loans Sold, Year-to-date","ACCT_SL0024 Number of First Mortgage loans sold on the secondary market, Year-to-date","ACCT_SL0026 Number of Loans Transferred with Limited Recourse Qualifying for Sales Accounting, Year-to-date","ACCT_SL0028 Number of Real Estate Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0029 Amount of Real Estate Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0030 Number of Outstanding Real Estate Loans Sold with Servicing Retained,"ACCT_SL0032 Number of All Other Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0033 Amount of All Other Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0034 Number of Outstanding All Other Loans Sold with Servicing Retained,ACCT_SL0035 Amount of Outstanding All Other Loans Sold with Servicing Retained,ACCT_LR0001 CCULR Election to opt into the Complex Credit Union Leverage Ratio,ACCT_LR0002 CCULR Off-Balance sheet exposures,ACCT_LR0003 CCULR Off-Balance sheet exposures ratio,ACCT_LR0004 CCULR Trading Assets and Trading Liabilities,ACCT_LR0005 CCULR Trading Assets and Trading Liabilities Ratio,ACCT_LR0006 CCULR Goodwill and Other Intangible Assets,ACCT_LR0007 CCULR Goodwill and Other Intangible Assets Ratio,ACCT_LR0008 Complex Credit Union Leverage Ratio Grace Period Indicator,ACCT_LQ0060 Borrowing Arrangements - Total Borrowing Capacity at Central Liquidity Facility,ACCT_LQ0061 Borrowing Arrangements - Total Borrowing Capacity at Federal Reserve Bank,ACCT_LQ0062 Borrowing Arrangements - Total Borrowing Capacity at FRB Paycheck Protrection Program Lending Facility,ACCT_NW0004 CECL Transition Provision (as determined under 702.703(c)),ACCT_PG0001 Legal Entity Identifier (LEI),ACCT_PP0037 Does the CU use financial technology companies to provide member services?,ACCT_PP0038 Auto Lending,ACCT_PP0039 Mortgage Lending,ACCT_PP0040 Secured personal loans,ACCT_PP0041 Unsecured personal loans,ACCT_PP0042 Lead generation for new members,ACCT_PP0043 Lead generation for share accounts,ACCT_PP0044 Acquire participation loans,ACCT_PP0045 Person-to-Person payments,ACCT_PP0046 Investment security exchange services,ACCT_PP0047 Communication,ACCT_PP0048 FinTech-Other,ACCT_PR0001 Located in Metropolitan Statistical Area (MSA),ACCT_PR0002 home purchase loan or refinanced a home purchase loan,ACCT_PR0003 Originated closed-end mortgages in each of the two preceding calendar years or originated open-end lines of credit in each of the two preceding calendar years in excess of the HMDA Loan-Volume Threshold?,ACCT_PR0004 Date of HMDA LAR filing,EligibleMinorityStatus Eligible Minority Status_dup,MemberMinorityStatus Member Minority Status_dup
0,1,2024-12-31,2,41785,5201,11835153,10456209,10456209,67353,2393,0,786,9163389,469,4090293,81375,0,1267,2000,0,0,153240,0,0.0,925.0,674.0,674.0,23905,1945,0,79339,6338306,203072,0,414057,0,97518,2031,0,0,462511,0,1121522,3576053,0,1173841,256,108382,0,0,...,0,10456209,10456209,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2475,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
1,6,2024-12-31,7,2868178,750856,269952063,204597639,235351639,1047124,799193,634163,20820,203270107,5184,70778947,3471204,0,29023,80000,0,12773,3414420,30754,1068.0,1195.0,542.0,699.0,2219598,495298,0,296365,114198488,0,0,14669290,0,2358767,5873183,7069093,30754000,43859975,4725698,23615053,37139099,2522257,22780119,3288,3442819,328530,1156943,...,8075368,204597639,235351639,30754000,306,5427305,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493006GFSNOUCCL1W91,1,1,1,1,1,0,0,0,1,0,1,0,1.0,1.0,1.0,Feb 20 2024 6:00AM,NaN,NaN
2,12,2024-12-31,11,4871838,488776,60540924,55308291,55308291,179249,29359,0,9419,32014515,5742,18715418,274845,0,9040,19040,0,15670,377490,0,1243.0,1050.0,800.0,875.0,542129,140015,0,218109,24132913,0,0,4775929,0,545246,175530,0,0,15803849,854722,2402616,4572449,9370441,6264516,345,135677,12335,0,...,0,55308290,55308290,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,254900TYE85Q9OTQ5038,1,0,0,0,1,0,0,0,0,0,0,0,1.0,1.0,1.0,Feb 21 2024 5:00AM,NaN,NaN
3,13,2024-12-31,12,18140884,2568776,1166537765,930699777,1013742211,1171283,617273,128431,37418,1017282706,15084,446216822,3378481,0,68058,849530,0,2367596,30175955,22,1100.0,950.0,364.0,364.0,3282767,627675,0,225269,162256236,0,0,25330954,0,8315000,4825426,55000000,83042434,117903239,33771244,264510694,522825843,31092281,93820486,12604,19288034,109569,0,...,224737959,930699777,1013742211,83042434,3,1094669,0,0,12,4270853,12,0,10,3952163,237,0,0,0,0,1,60620062,519,0,0,0,0,0,225000000,0,0,751817,549300U18MOAH5F95P15,1,1,0,0,0,0,0,0,1,0,1,0,1.0,1.0,1.0,Feb 14 2024 6:00AM,NaN,NaN
4,16,2024-12-31,14,0,2147,9364728,8039127,8039127,513,0,13624,279,3591866,60,932229,14550,0,866,1320,0,45,52118,0,1490.0,1000.0,649.0,674.0,21311,6300,0,0,4862022,479075,0,367390,34690,80311,6080,0,0,1702619,166167,1308317,1308317,0,815137,73,0,0,0,...,0,8039125,8039125,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,1,0,1,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4545,97109,2024-12-31,2759,6101495,533784,478268143,414728132,414728132,787949,205201,4204,18722,373691149,4042,104064173,1897562,0,26038,500000,0,652897,8516588,0,1450.0,1349.0,649.0,729.0,1384678,391857,0,1132554,105957740,0,0,14022092,0,0,4440162,12343587,0,76719657,15189973,93516755,127792332,81155987,48713684,6398,5069806,108536,46259005,...,49970737,414728132,414728132,0,0,0,0,0,15,1136310,0,0,15,790790,88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493001D5DXR1S70P689,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4546,97110,2024-12-31,17502,15082080,937791,401737330,346422530,346422530,891830,416109,205205,13718,256663866,2326,53918974,2701970,0,24452,255994,0,157628,5795716,0,1699.0,1249.0,649.0,799.0,1324290,100237,0,7219294,63929423,0,0,14180884,0,0,2748692,20000000,0,78095389,8308102,82503871,96177182,89289929,30814315,2351,3448749,129168,4550289,...,29012427,346422530,346422530,0,0,0,0,0,17,5543760,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7542011,0,354783,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4547,97111,2024-12-31,21049,4791549,656334,174674528,155782331,157296566,237391,95414,41,7725,136292934,2702,62481728,571752,0,13565,900000,0,214358,2549987,4,1264.0,1122.0,572.0,705.0,481311,132212,0,216473,52476536,0,0,6088709,0,0,747250,6000000,1514235,30377515,5428128,44833552,52323024,13268216,12550039,2817,1866980,24471,43784169,...,12241376,155782331,157296566,1514235,2389,3587872,49,4354839,21,5710637,9,0,12,4335591,18,0,0,2,496586,0,0,0,0,0,0,0,0,0,0,0,0,549300N1MCHMZQ2BP498,1,1,1,1,1,0,0,0,0,0,1,0,1.0,1.0,1.0,Feb 8 2024 5:00AM,NaN,NaN
4548,97112,2024-12-31,22698,8099948,527890,235690662,223637998,223637998,537385,156189,0,11383,129024858,2051,39061167,1227052,0,21442,3600578,0,2743,2914316,0,830.0,920.0,523.0,537.0,1028815,84612,0,0,91918143,0,0,8900891,0,0,882935,0,0,49471265,11075579,38928379,57370547,10927916,26982031,3497,2847665,143508,0,...,2962702,223637998,223637998,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,1.0,1.0,NaN,NaN,NaN,NaN
4549,97113,2024-12-31,8532,672452,165479,71256872,62654589,62654589,35219,196,0,4025,43525418,699,9215791,138403,0,8003,25000,0,294,922526,0,883.0,1063.0,537.0,630.0,257672,65974,0,4923130,20950204,0,0,2495239,0,0,292278,0,0,11367445,850799,9255550,10567396,13636351,8310005,828,135608,36788,1048279,...,1240846,62654590,62654590,0,0,0,0,0,0,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4681,549300snbyrug0bk5t32,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

# Common Columns Among all Dataframes

In [578]:
df_march_cols = set(combined_wide_march.columns)
df_june_cols = set(combined_wide_june.columns)
df_sep_cols = set(combined_wide_sep.columns)
df_dec_cols = set(combined_wide_dec.columns)

In [579]:
all_unique_cols = df_march_cols.union(df_june_cols, df_sep_cols, df_dec_cols)

In [580]:
len(all_unique_cols)

1217

In [581]:
cols_missing_from_march = all_unique_cols - df_march_cols
cols_missing_from_june = all_unique_cols - df_june_cols
cols_missing_from_sep = all_unique_cols - df_sep_cols
cols_missing_from_dec = all_unique_cols - df_dec_cols

In [582]:
cols_missing_from_march

{'EligibleMinorityStatus Eligible Minority Status_dup',
 'MemberMinorityStatus Member Minority Status_dup'}

In [583]:
cols_missing_from_june

{'EligibleMinorityStatus Eligible Minority Status_dup',
 'MemberMinorityStatus Member Minority Status_dup'}

In [584]:
cols_missing_from_sep

{'EligibleMinorityStatus Eligible Minority Status_dup',
 'MemberMinorityStatus Member Minority Status_dup'}

In [585]:
cols_missing_from_dec

{'ACCT_PG0002 Anti-money laundering monitoring system',
 'ACCT_PP0049 Does the CU offer cryptocurrency services to members',
 'ACCT_PP0050 Exchange services',
 'ACCT_PP0051 Non-custodial wallets',
 'ACCT_PP0052 Custodial wallets',
 'ACCT_PP0055 Mobile application',
 'ACCT_PP0056 Crypto-Other',
 'ACCT_PP0057 Does the CU use blockchain or distributed ledger technology?',
 'EligibleAfricanAmerican Eligible African American',
 'EligibleAsianAmerican Eligible Asian American',
 'EligibleHispanicAmerican Eligible Hispanic American',
 'EligibleNativeAmerican Eligible Native American',
 'MemberAfricanAmerican Member African American',
 'MemberHispanicAmerican Member Hispanic American',
 'MemberNativeAmerican Member Native American'}

In [586]:
dfs = [combined_wide_march, combined_wide_june, combined_wide_sep, combined_wide_dec]

common_cols = set.intersection(*(set(df.columns) for df in dfs))

In [587]:
len(common_cols)

1200

# Concatenate March, June, Sep, Dec

In [588]:
cu_2024 = pd.concat([combined_wide_march, combined_wide_june, combined_wide_sep, combined_wide_dec],\
                    axis=0, join="outer")

In [589]:
cu_2024.tail()

,CU_NUMBER,CYCLE_DATE,JOIN_NUMBER,ACCT_007 Land and Building,ACCT_008 Other Fixed Assets,ACCT_010 TOTAL ASSETS,ACCT_013 Total Amount of Shares,ACCT_018 Total Amount of Shares and Deposits,ACCT_021B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 2 to less than 6 months delinquent,ACCT_022B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 6 to less than 12 months delinquent,ACCT_023B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 12 months and over delinquent,ACCT_025A Total number of Loans and Leases,ACCT_025B Total amount of Loans and Leases,ACCT_031A Loans Granted Year-to-Date,ACCT_031B Amount of Loans Granted Year-to-Date,ACCT_041B Total Amount of Delinquent Loans & Leases (Two or more months),"ACCT_058C Borrowing Repurchase Transactions, Total Amount",ACCT_083 Number of current members (not number of accounts),ACCT_084 Number of potential members,ACCT_300 Provision for Loan & Lease Losses,ACCT_340 Interest on Borrowed Money,ACCT_380 Dividends on Shares (Includes dividends earned during current period),ACCT_457 Non-Member Deposits,ACCT_521 Interest Rate of Unsecured Credit Card Loans,ACCT_522 Interest Rate of All Other Unsecured Loans/Lines of Credit,ACCT_523 Interest Rate of New Vehicle Loans,ACCT_524 Interest Rate of Used Vehicle Loans,ACCT_550 Total Amount of All Loans Charged Off Year-to-Date,ACCT_551 Total Amount of All Year-to-Date Recoveries on Charged-Off Loans,ACCT_602 Net Income (unless the amount is already included in Undivided Earnings),ACCT_630 Total Amount of All Other Shares,ACCT_657 Amount of Regular Shares,ACCT_658 Other Reserves (Appropriations for Undivided Earnings),ACCT_668 Appropriation for Non-Conforming Investments (SCU ONLY),ACCT_671 Total Non-Interest Expense (Sum of items 18-27),ACCT_719 Less: Allowance for Loan & Lease Losses,ACCT_794 NCUA Share Insurance Capitalization Deposit,ACCT_825 Accounts Payable and Other Liabilities,ACCT_860C Total Borrowings,ACCT_880 Total Amount of Non-Member Deposits,ACCT_902 Amount of Share Drafts,ACCT_906A IRA/KEOGH Accounts - < 1 Year,ACCT_908A Share Certificates - < 1 Year,ACCT_908C Total Amount of Share Certificates,ACCT_911 Total Amount of Money Market Shares,ACCT_940 Undivided Earnings,ACCT_968 Number of Used Vehicle Loans,ACCT_020B Amount of All Deliquent Loans (Including Credit Cards) and Leases as of - 1 month to less than 2 months delinquent,ACCT_024B Amount of Delinquent Unsecured Credit Card Loans as of - 1 month to less than 2 months delinquent.,ACCT_400A Net Member Business Loan Balance,...,"ACCT_SL0022 Number of Loans Sold, Year-to-date","ACCT_SL0023 Amount of Loans Sold, Year-to-date","ACCT_SL0024 Number of First Mortgage loans sold on the secondary market, Year-to-date","ACCT_SL0026 Number of Loans Transferred with Limited Recourse Qualifying for Sales Accounting, Year-to-date","ACCT_SL0028 Number of Real Estate Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0029 Amount of Real Estate Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0030 Number of Outstanding Real Estate Loans Sold with Servicing Retained,"ACCT_SL0032 Number of All Other Loans Sold with Servicing Retained, Year-to-date","ACCT_SL0033 Amount of All Other Loans Sold with Servicing Retained, Year-to-date",ACCT_SL0034 Number of Outstanding All Other Loans Sold with Servicing Retained,ACCT_SL0035 Amount of Outstanding All Other Loans Sold with Servicing Retained,ACCT_LR0001 CCULR Election to opt into the Complex Credit Union Leverage Ratio,ACCT_LR0002 CCULR Off-Balance sheet exposures,ACCT_LR0003 CCULR Off-Balance sheet exposures ratio,ACCT_LR0004 CCULR Trading Assets and Trading Liabilities,ACCT_LR0005 CCULR Trading Assets and Trading Liabilities Ratio,ACCT_LR0006 CCULR Goodwill and Other Intangible Assets,ACCT_LR0007 CCULR Goodwill and Other Intangible Assets Ratio,ACCT_LR0008 Complex Credit Union Leverage Ratio Grace Period Indicator,ACCT_LQ0060 Borrowing Arrangements - Total Borrowing Capacity at Central Liquidity Facility,ACCT_LQ0061 Borrowing Arrangements - Total Borrowing Capacity at Federal Reserve Bank,ACCT_LQ0062 Borrowing Arrangements - Total Borrowing Capacity at FRB Paycheck Protrection Program Lending Facility,ACCT_NW0004 CECL Transition Provision (as determined under 702.703(c)),ACCT_PG0001 Legal Entity Identifier (LEI),ACCT_PG0002 Anti-money laundering monitoring system,ACCT_PP0037 Does the CU use financial technology companies to provide member services?,ACCT_PP0038 Auto Lending,ACCT_PP0039 Mortgage Lending,ACCT_PP0040 Secured personal loans,ACCT_PP0041 Unsecured personal loans,ACCT_PP0042 Lead generation for new members,ACCT_PP0043 Lead generation for share accounts,ACCT_PP0044 Acquire participation loans,ACCT_PP0045 Person-to-Person payments,ACCT_PP0046 Investment security exchange services,ACCT_PP0047 Communication,ACCT_PP0048 FinTech-Other,ACCT_PP0049 Does the CU offer cryptocurrency services to members,ACCT_PP0050 Exchange services,ACCT_PP0051 Non-custodial wallets,ACCT_PP0052 Custodial wallets,ACCT_PP0055 Mobile application,ACCT_PP0056 Crypto-Other,ACCT_PP0057 Does the CU use blockchain or distributed ledger technology?,ACCT_PR0001 Located in Metropolitan Statistical Area (MSA),ACCT_PR0002 home purchase loan or refinanced a home purchase loan,ACCT_PR0003 Originated closed-end mortgages in each of the two preceding calendar years or originated open-end lines of credit in each of the two preceding calendar years in excess of the HMDA Loan-Volume Threshold?,ACCT_PR0004 Date of HMDA LAR filing,EligibleMinorityStatus Eligible Minority Status_dup,MemberMinorityStatus Member Minority Status_dup
4545,97109,2024-12-31,2759,6101495,533784,478268143,414728132,414728132,787949,205201,4204,18722,373691149,4042,104064173,1897562,0,26038,500000,0,652897,8516588,0,1450.0,1349.0,649.0,729.0,1384678,391857,0,1132554,105957740,0,0,14022092,0,0,4440162,12343587,0,76719657,15189973,93516755,127792332,81155987,48713684,6398,5069806,108536,46259005,...,15,1136310,0,0,15,790790,88,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5493001D5DXR1S70P689,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4546,97110,2024-12-31,17502,15082080,937791,401737330,346422530,346422530,891830,416109,205205,13718,256663866,2326,53918974,2701970,0,24452,255994,0,157628,5795716,0,1699.0,1249.0,649.0,799.0,1324290,100237,0,7219294,63929423,0,0,14180884,0,0,2748692,20000000,0,78095389,8308102,82503871,96177182,89289929,30814315,2351,3448749,129168,4550289,...,17,5543760,17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7542011,0,354783,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4547,97111,2024-12-31,21049,4791549,656334,174674528,155782331,157296566,237391,95414,41,7725,136292934,2702,62481728,571752,0,13565,900000,0,214358,2549987,4,1264.0,1122.0,572.0,705.0,481311,132212,0,216473,52476536,0,0,6088709,0,0,747250,6000000,1514235,30377515,5428128,44833552,52323024,13268216,12550039,2817,1866980,24471,43784169,...,21,5710637,9,0,12,4335591,18,0,0,2,496586,0,0,0,0,0,0,0,0,0,0,0,0,549300N1MCHMZQ2BP498,NaN,1,1,1,1,1,0,0,0,0,0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,Feb 8 2024 5:00AM,NaN,NaN
4548,97112,2024-12-31,22698,8099948,527890,235690662,223637998,223637998,537385,156189,0,11383,129024858,2051,39061167,1227052,0,21442,3600578,0,2743,2914316,0,830.0,920.0,523.0,537.0,1028815,84612,0,0,91918143,0,0,8900891,0,0,882935,0,0,49471265,11075579,38928379,57370547,10927916,26982031,3497,2847665,143508,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN
4549,97113,2024-12-31,8532,672452,165479,71256872,62654589,62654589,35219,196,0,4025,43525418,699,9215791,138403,0,8003,25000,0,294,922526,0,883.0,1063.0,537.0,630.0,257672,65974,0,4923130,20950204,0,0,2495239,0,0,292278,0,0,11367445,850799,9255550,10567396,13636351,8310005,828,135608,36788,1048279,...,0,0,0,0,0,0,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4681,549300snbyrug0bk5t32,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [590]:
cu_2024.shape

(18447, 1217)

# Slice Columns into Manageable Sets

1. **By data availability: drop columns that are 95%+ missing**

In [597]:
cu_2024 = cu_2024.loc[:, cu_2024.isna().mean() <= 0.05]

In [598]:
cu_2024.shape

(18447, 1185)

2. **Group Variables into Broader Themes**

In [603]:
def search_columns(df, keyword: str):
    return [col for col in df.columns if keyword.lower() in col.lower()]

In [606]:
assets = search_columns(cu_2024, 'asset')
income = search_columns(cu_2024, 'income')
loans = search_columns(cu_2024, 'loan')
delinquencies = search_columns (cu_2024, 'delinquency')

63